import React, { Component } from 'react'
import { Header } from '../common/Header/Header';
import './staticPages.scss';

export class Legality extends Component {
    render() {
        let fields = {
            title: 'Legality', 
            sideToggle: false,
            crossButton: {
                showFlag: false,
            },
            backButton: {
                showFlag: true,
                url: 'goback',
            },
            styleCss:{
                background: '#FFFFFF', 
                text: '#000000'
            }, 
            'points': false, 
            'wallet': false
        };
        return (
            <div>
                <Header fields={fields} />
                <div className="static-content content col-12">
                    <p>This privacy policy applies to the entire contents of the platform “GullyPro” operated by Mindsarray Network Pvt Ltd which offers fantasy cricket gaming and may be referred to hereon in as "we" or "us" or "our" (as applicable) including, without limitation, www.gullypro.com or any web (including any associated Facebook application), partner website(s) or software used to access the platform [collectively referred to as the “Portal”].</p>
                    <p>Please read the Privacy Policy below carefully before using Gullypro. By using or registering on Gullypro, you accept and agree to the terms of this Privacy Policy. If you do not accept these terms, you will not be allowed to access Gullypro. Any person utilizing the Portal (“User” or “you” or “your”) or any of its features including participation in the various contests, games (including fantasy games ("Game") (“Amusement Facilities”) being conducted on the Portal) shall be bound by this Privacy Policy.</p>
                    <p>The Users are responsible for ensuring that we keep their information current and accurate. The Users may update their information by contacting us at info@gullypro.com, and we will use reasonable efforts to process any change the User makes; provided, however, that requests to delete information are subject to Gullypro’s internal reporting, processing and retention policies and all applicable legal obligations and existing legislations.</p>
                    <p>We at Gullypro are committed to preserving the privacy of all visitors to our platform Gullypro. We are committed to ensuring that all services and activities made available via the platform Gullypro will be provided in a safe and secure online environment. By accepting Gullypro’s Privacy Policy and the Terms & Conditions at the time of registration, you expressly consent to our use and disclosure of your personal information in accordance with this Privacy Policy. This Privacy Policy is incorporated into and subject to Gullypro’s Terms & Conditions. This Privacy Policy is effective upon acceptance in registration for new registering users.</p>
                    <p>With a view to offer an enriching and holistic internet experience to its Users, Gullypro offers a vast repository of Amusement Facilities. Kindly take time to read the 'About Us' section to know more about Gullypro. Most of the Amusement Facilities are offered for free but you may need registration to participate in some of Gullypro’s online games.</p>
                    <p>Before you submit any information to the Portal, please read this Privacy Policy for an explanation of how we will treat your personal information. By using any part of the Portal, you consent to the collection, use, disclosure and transfer of your personal information for the purposes outlined in this Privacy Policy and to the collection, processing and maintenance of this information. If you do not agree to this Privacy Policy, please do not use the Portal. Your use of any part of the Portal indicates your acceptance of this Privacy Policy and of the collection, use and disclosure of your personal information in accordance with this Privacy Policy. While you have the option not to provide us with certain information or withdraw consent to collect certain information, kindly note that in such an event you may not be able to take full advantage of the entire scope of features and services offered to you and we reserve the right not to provide you with our services.</p>
                    <p><strong>Your Privacy: Our Commitment</strong></p>
                    <p>At Gullypro, we are extremely proud of our commitment to protect your privacy and recognise that you have a right to know about the information we access or collect about you, how your information is being used by us and what we do to protect your information. Please read the following policy to understand how your personal information shall be treated by Gullypro.</p>
                    <p>Our commitment towards privacy and protection of User data is based on the principles of lawfulness, transparency, fairness, accuracy, data minimisation, integrity and confidentiality.</p>
                    <p><strong>What does this Privacy Policy Cover?</strong></p>
                    <p>This Privacy Policy is part of Gullypro’s Terms & Conditions and covers the treatment of user information, including personally identifying information, obtained by Gullypro including information obtained when you access Gullypro’s Portal and any information that you may share through use of the Gullypro Portal.</p>
                    <p><strong>Introduction</strong></p>
                    <p>Gullypro (“Gullypro, we, us”) recognizes that people who use Gullypro’s service (“you” or “Users”) value their privacy. This Privacy Policy details important information regarding the collection, use and disclosure of User information collected on Gullypro’s skill based gaming website located at www.gullypro.com and/or the related mobile application (including any associated Facebook application), partner website(s) or software used to access the Gullypro platform [collectively referred to as the “Portal”], and any other features, tools, materials, or other services (including co-branded or affiliated services) offered from time to time by Gullypro or its affiliate companies (collectively referred to as the “Service”). Gullypro provides this Privacy Policy to help you make an informed decision about whether to use or continue using the Portal and/or Service.</p>
                    <p>This Privacy Policy should be read in conjunction with our Terms & Conditions. By accessing the Portal and/or Service, you are consenting to the collection and use of information practices described in this Privacy Policy.
                    The User’s use of the Portal and/or Service and any information the User may provide through the Portal and/or Service remains subject to the terms of this Privacy Policy and our Terms & Conditions, as each may be updated from time to time.
                    The User through access of the Portal and/or Service and acceptance of this Privacy Policy, hereby warrants and accepts that he/she has given her explicit and unequivocal consent to Gullypro for collection and processing of his/her personal information and that the said collection and processing of his/her personal information is necessary for Gullypro to fulfil their obligations for the provision of skill based gaming services to the said User and the User’s participation on the said skill based gaming platform of Gullypro.</p>
                    <p>Any questions, comments or complaints that you might have should be emailed to info@gullypro.com or forwarded in writing to: 5584, Third Floor, Naya bazar, Delhi - 110006</p>
                    <p>www.gullypro.com operates the portal in India, which offers cricket fantasy games through the web-portal www.gullypro.com and associated Facebook application, partner website(s) and mobile application(s) (collectively referred to as the “Portal”) (www.gullypro.com referred to herein as “www.gullypro.com” or “we” or “us” “our”).</p>
                    <p>Any person utilizing the Portal (“User” or “you” or “your”) or any of its features including participation in the various contests, games (including fantasy games ("Game") (“Amusement Facilities”) being conducted on the Portal) shall be bound by this Privacy Policy.</p>
                    <p>www.gullypro.com respects the privacy of its Users and is committed to protect it in all respects. With a view to offer an enriching and holistic internet experience to its Users, www.gullypro.com offers a vast repository of Amusement Facilities. Kindly take time to read the 'About Us' section to know more about www.gullypro.com. Most of the Amusement Facilities are offered for free but you may need registration to participate in www.gullypro.com's online games. The information about the User is collected by www.gullypro.com as (i) information supplied by Users and (ii) information automatically tracked during User's navigation on www.gullypro.com.</p>
                    <p>Before you submit any information to the Portal, please read this Privacy Policy for an explanation of how we will treat your personal information. By using any part of the Portal, you consent to the collection, use, disclosure and transfer of your personal information for the purposes outlined in this Privacy Policy and to the collection, processing and maintenance of this information. If you do not agree to this Privacy Policy, please do not use the Portal. Your use of any part of the Portal indicates your acceptance of this Privacy Policy and of the collection, use and disclosure of your personal information in accordance with this Privacy Policy. While you have the option not to provide us with certain information or withdraw consent to collect certain information, kindly note that in such an event you may not be able to take full advantage of the entire scope of features and services offered to you and we reserve the right not to provide you with our services.</p>
                    <p><strong>Information Collected from UsersPurpose and Usage:</strong></p>
                    <p>By choosing to use our Portal and/or Service and by submitting information to us through your use of our Portal/Service then this Privacy Policy will apply. You provide certain personal information to Gullypro when choosing to participate in the various activities on the Portal/Service such as registering for an account, participating in contests, posting messages, taking advantage of promotions, responding to surveys or subscribing to newsletters or other mailing lists.</p>
                    <p>The information may be collected from the User in a number of ways which may include collecting personal information if the User chooses to create an account with us, thereby agreeing with the Terms and Conditions and accepting the Privacy Policy of Gullypro while entering the same. The User may also be required to complete an online survey or feedback form, sign up or email us to receive communications from us. <u>We may also ask the User to provide information regarding his/her contact details including name, email address, mailing address, telephone number, age, gender, date of birth, credit card & billing information, profile picture, username & account passwords, locations, responses to surveys, communications sent by you to us etc.</u></p>
                    <p>In addition to the above, we may need to verify your identity in order for you to use some aspects of the Portal/Service. For purposes of verification, we may also collect the following personal information from you:</p>
                    <ul>
                        <li>Passport information;</li>
                        <li>Aadhar Card information and details;</li>
                        <li>PAN Card information;</li>
                        <li>Government-issued residence proof;</li>
                        <li>User's bank account details and proof of the same;</li>
                        <li>Tax-related information; and</li>
                        <li>Other information as may be required to verify you in accordance with applicable laws and regulations.</li>
                    </ul>
                    <p>Any information provided by the User through your posts or your comments, opinions and/or feedback uploaded on the Public Forum of the Gullypro Portal.</p>
                    <p>In the course of using the Portal/Service, Users may invite other existing Users or other users (“Invited Users”) to participate in any of the games by providing the email address or Facebook username of such users. Gullypro may thereafter use this information to contact the Invited User and invite such user to register with Gullypro (if such Invited User is not an existing User) and participate in the games in relation to which such person was invited by the User. The participation of the Invited User in any of the games on the Portal shall be subject to the terms of this Privacy Policy and the Terms and Conditions for the use of the Portal.</p>
                    <p>We may require you to furnish information about the payment methods such as credit/debit cards, e-wallets and other online payment methods. We may also require you to furnish additional information about the same including but not limited to billing address, card type, number, expiration date, card security code, transaction code and/or receipt etc. If you choose to access Portal and/or any Service of Gullypro which requires payments, you may be required to furnish the above stated details.</p>
                    <p>When you use our mobile app, you hereby consent to us accessing the features of your mobile device such as the phone number, your contacts, IMEI number of your device, whether a phone call is active, the number that the phone call is connected to and the like. The access to your mobile phone device features is used to stop the radio commentary and terminate the internet access when you make or receive a call without any disruption.</p>
                    <p>When you use our mobile app, we also may collect mobile device information like operating system and hardware type, numbers or codes that are unique to your particular device (such as IDFA or an Android Ad ID), device information, default device language, the location of your device (at a GPS level), and app usage information. This data also may be linked to your other information, including your location data.</p>
                    <p>In addition, if you choose to log in, access or otherwise connect to Gullypro, or contact Gullypro, through a social networking service or any third party service (such as Facebook, Twitter, Google etc), we may collect your user ID and user name associated with that social networking service or third party service, as well as any information you make public using that social networking service or third party service. We may also collect information you have authorized the social networking service or third-party service to share with us (such as your user ID, public profile information, email address, birthday, friends list, and pages you have "liked" or tweeted).</p>
<p>We may collect and process the information such as names, photos, contact details, the User&rsquo;s activity during the tournament games, posts and comments pertaining to Gullypro.</p>
<p>Cookies Information: When you visit the Gullypro Portal, we may send one or more cookies - small files - to your computer or other device, which may enable us or others to uniquely identify your browser. A cookie is a file containing an identifier (a string of letters and numbers) that is sent by a web server to a web browser and is stored by the browser. The identifier is then sent back to the server each time the browser requests a page from the server. This enables the web server to identify and track the web browser.</p>
<p>Gullypro may use both session cookies and persistent cookies. A persistent cookie remains after you close your browser. Persistent cookies may be used by your browser on subsequent visits to the site. Persistent cookies can be removed by following your web browser help file directions. Session cookies are temporary and typically disappear after you close your browser. You may be able to reset your web browser to refuse all cookies or to indicate when a cookie is being sent. However, some features of the Portal or Service may not function properly if the ability to accept cookies is disabled.</p>
<p>We use the session cookies to keep track of you whilst you navigate the Portal/Service to prevent frauds and increase website security. We use the persistent cookies to enable our Portal to recognize you when you visit and keep track of your preferences in relation to your usage of our website.</p>
<p>We use Google Analytics to analyze the usage of this Portal/Service. Google Analytics generates statistical and other information about website use by means of cookies, which are stored on users' computers. The information generated relating to our Portal/Service is used to create reports about the use of the Portal/Service. Google will store this information and Google's privacy policy is available at:&nbsp;<a href="http://www.google.com/privacypolicy.html">http://www.google.com/privacypolicy.html</a>.</p>
<p>You can manage your preferences relating to the use of cookies on our Portal/Service by visiting www.gullypro.com. Most browsers allow you to reject all cookies, whilst some browsers allow you to reject just third-party cookies. For example, in Internet Explorer (version 9) you can refuse all cookies by clicking "Tools"&gt; "Internet options"&gt; "Privacy" and selecting "Block All Cookies" using the sliding selector. Blocking all cookies may, however, have a negative impact upon the usability of many websites including our Portal/Service.</p>
<p>Log File Information: When you use our Portal/Service, our servers may automatically record certain information that your device sends whenever you visit any website and use certain apps. These server logs may include information such as your web or app request, Internet Protocol ("IP") address, browser type, browser language, referring/exit pages and URLs, platform type, number of clicks, domain names, landing pages, pages viewed and the order of those pages, the amount of time spent on particular pages, the date and time of your request, the actions you take on a page and one or more cookies that may uniquely identify your browser.</p>
<p>Clear GIFs Information: When you use our Portal/Service, we may employ technology such as "clear GIFs" (a.k.a. Web Beacons) which are used to track the online usage patterns of our users. In addition, we may also use clear GIFs in HTML-based emails sent to our users to track which emails are opened by specific users.</p>
<p>Third Party Sites &amp; the User</p>
<p>The Gullypro website and/or the App (collectively referred to as &ldquo;Portal&rdquo;) may include links to other third-party websites or web pages. Such sites or pages are governed by their respective terms &amp; conditions and privacy policies, which are beyond our control. Once you exit the Gullypro Portal and enter a third-party site through the Gullypro Portal, use of any information you provide shall be governed by the privacy policy and/or terms and conditions of the operator of the particular site you are visiting. Gullypro shall not, under any circumstances, be responsible for any use of third-party site by such User.</p>
<p>Gullypro refuses to acknowledge or represent the accuracy, completeness, reliability or adequacy of the Portal's third-party content. The content, materials, information, services and products in the Portal including text, graphics and links, are provided "AS IS" and without warranties of any kind, whether expressed or implied. Gullypro is in no way responsible for any content of any linked site or any link contained in a linked site.</p>
<p>Gullypro disclaims all warranties, expressed and implied with regards to the merchantability and fitness of the Portal and/or such third-party sites for a particular purpose. Gullypro also does not guarantee that users shall be able to use the Portal and/or such third-party websites without any interruption, which may lead to loss in continuity.</p>
<p>Although, Gullypro shall make reasonable efforts to ensure that the Portal remains free of viruses or other harmful components, however, Gullypro does not in any way represent or warrant that the Portal or the server that makes the Portal available shall be free of such harmful components. Use of the services of this Portal is at User's own risk and Gullypro shall not be responsible for any servicing costs, repair or correction of the User&rsquo;s systems.</p>
<p>Gullypro does not, in any manner whether express or implied, endorse the advertisements hosted on its Portal and the Users responding to such advertisements and/or purchasing any products advertised on Gullypro hereby warrant and accept that they shall do so at their own risk.</p>
<p>Gullypro reserves all rights to the assets, content, services, information and products and graphics in the Portal except any third-party content.</p>
<p>To avail certain Amusement Facilities on the Portal, Users would be required to provide certain information for the registration process namely:</p>
<ol>
<li>Password</li>
<li>Email address</li>
<li>Date of birth</li>
</ol>
<p>In the course of providing you with access to the Amusement Facilities, and in order to provide you access to the features and services offered through the Portal and to verify your identity, you may be required to furnish additional information, including your Permanent Account Number.</p>
<p>In the course of providing you with access to the Amusement Facilities, and in order to provide you access to the features and services offered through the Portal and to verify your identity, you may be required to furnish additional information, including your Permanent Account Number. In the course of providing the Amusement Facilities, Users may invite other existing Users or other users (&ldquo;Invited Users&rdquo;) to participate in any of the Amusement Facilities by providing the email address or Facebook username of such users. www.gullypro.com may thereafter use this information to contact the Invited User and invite such user to register with www.gullypro.com (if such Invited User is not a existing User) and participate in the Game/Amusement Facility in relation to which such person was invited by the User. The participation of the Invited User in any of the Amusement Facilities shall be subject to the terms of this Privacy Policy and the Terms and Conditions (https://www.gullypro.com/terms.html) for the use of the Portal. The User hereby represents that the Invited Users have consented and agreed to such disclosure to and use of their email address and Facebook username by www.gullypro.com.</p>
<p>All required information is specific and based on the kind of Game/ Amusement Facility the User wishes to participate in or access, and will be utilized for the purpose of providing services, including but not limited to the Amusement Facility, requested by the User. The information as supplied by the Users enables us to improve the Amusement Facilities and provide you the most user-friendly game experience. gullypro may also share such information with affiliates and third parties in limited circumstances, including for the purpose of providing services requested by the User, complying with legal process, preventing fraud or imminent harm, and ensuring the security of our network and services.</p>
<p>Use of Information by Gullypro</p>
<p>We may use your personal information to operate and maintain the Portal/Service. The information may also be used to provide to you the features and functionality of the Portal/Service, including but not limited to the following:</p>
<ul>
<li>Administering the Portal/Service and enabling its use for the User;</li>
<li>Providing you with our products, services, games including their updates;</li>
<li>Processing and responding to your enquiries or feedback;</li>
<li>Personalizing your use of the Portal/Service,</li>
<li>Alerting you to new features, special events, products and services, or certain third-party products or services in which we think you will be interested;</li>
<li>Sending statements and invoices to you and collecting payments from you;</li>
<li>Enforcing the legal terms and conditions that govern your use of the Portal/Service;</li>
<li>Investigating and protecting the integrity of Gullypro&rsquo;s Games and/or Tournaments and/or Leagues and/or Challenges and keeping the Portal/Service secure;</li>
<li>Dealing with customer inputs, complaints and suggestions; and</li>
<li>Contacting you about your account or profile.</li>
</ul>
<p>We may use your information (both personal and non-personal information) to send you marketing and advertising content, including sending you advertising through multiple channels, such as direct mail, email, push notifications and display media. We may send you advertising or content regarding our products and services, or products and services that we market on behalf of another company or any other entity.</p>
<p>We may use your information to communicate with you about:</p>
<ul>
<li>Our products and services in which you may be interested provided that you have not requested otherwise;</li>
<li>Newsletters and information for which you have signed up; and</li>
<li>Non-marketing or administrative purposes (such as notifying you of major changes to the Portal/Service or for customer service purposes).</li>
</ul>
<p>We use your information to improve the quality and design of our Portal/Service and to create new features, promotions, functionality, and services such as by storing, tracking, and analyzing user preferences and trends.</p>
<p>We may use the information collected from you in order to process payment fees.</p>
<p>We may use your information in order to implement sufficient credit fraud protection and risk reduction measures.</p>
<p>We also use cookies, clear gifs, log file information, and mobile app information such as device identifiers for purposes such as (a) remembering information so that you will not have to re-enter it during your visit or the next time you visit our Portal/Service; (b) providing custom, personalized content and information; (c) monitoring the effectiveness of our marketing campaigns; (d) monitoring aggregate metrics such as total number of visitors, pages viewed, etc.; and (e) tracking your entries, submissions, and status in promotions, sweepstakes, and contests.&nbsp;You can learn more about how these technologies are used in the Section below: Third Party Advertising and Analytics.</p>
<p>We may anonymize, de-identify, or aggregate your information for any legitimate business purposes, including for reporting and research, or advertising. Such anonymized and/or aggregated data does not personally identify you. Sometimes, this information may be used to target more relevant content or offers to you across different devices &ndash; for instance, we may provide you with offers and content on your mobile device, based on your web-based activity.</p>
<p>We may use the information collected from you to verify User compliances with the Terms and Conditions and/or Privacy Policy governing the use of the Portal/Service including monitoring private messages sent through our Portal/Service private messaging service. Your privacy settings can be used to limit the publication of your information on the Portal/Service. You can adjust your privacy settings by contacting us at&nbsp;<a href="mailto:info@apne11.com">info@gullypro.com</a></p>
<p>We may disclose the information provided to us by the User for any other reason the User provided us with the said information.</p>
<p>When Gullypro Discloses Informationure/Sharing:</p>
<p>We may disclose the information we collect or receive from you to our subsidiaries, affiliated companies, agents, or other businesses, or service providers who process your information on our behalf in order to provide or operate the Portal/Service. For instance, these entities may have access to your information for purposes including (but not limited to) billing and accounting, hosting, marketing, promotional and email services, customer and technical support, and for the purpose of accepting deposits and paying withdrawals and processing such information on our behalf, and in each case, may use the information to make improvements to the services they provide to us. Our agreements with these service providers limit the kinds of information they can use or process and require them to use reasonable efforts to keep your personal information secure.</p>
<p>When you choose to share information with social media services about your activities on Gullypro by, for example, connecting your social media account to our Portal/Service, then Gullypro may share your personal information and information about your use of the Portal/Service with such social media sites. Please make sure to read the terms and conditions and privacy statements of such sites prior to connecting to our Portal/Service in this way.</p>
<p>In the event that you win a prize we may contact you using your personal information (such as your name and photo) in connection with publicity purposes.</p>
<p>In the event that you win a promotion run by us we may be required to either publish or make available upon request: your name and country/state in accordance with applicable legislation.</p>
<p>We may publish a profile page that includes your username, the date you became a member, your stats from previous games and, if you uploaded one, your profile picture. Where you post personal information about yourself through our Portal/Service to public areas of our Portal/Service, you acknowledge and agree that this personal information will be publicly available.</p>
<p>When you participate in a contest, we may publish your username on a list of the contest participants, along with a link to your profile page.</p>
<p>Where you have provided your consent, we may share your personal information with selected third parties for their commercial or marketing use in conjunction with your relationship with Gullypro or as part of a specific program or feature.</p>
<p>In addition, we may disclose to third-parties various types of your information for targeted online or mobile advertising, as further described in the Section titled &ldquo;Third Party, Sharing Advertising and Analytics.&rdquo;</p>
<p>We also may share personal information in other situations with your consent.</p>
<p>Gullypro also reserves the right to disclose personal information that Gullypro believes, in good faith, is appropriate or necessary to enforce our Terms of Use/Terms &amp; Conditions, take precautions against liability or harm, to investigate, prevent and/or respond to third-party claims or allegations, suspected illegal activities, fraud, to respond to court orders or official requests, to comply with state/central legal regulations, including but not limited to sharing with appropriate tax authorities, to protect the security or integrity of our Portal/Service, to report violations of Gullypro&rsquo;s eligibility rules to third parties or safety of Gullypro, our users or others.</p>
<p>If you elect to participate in any promotions, surveys, questionnaires, or other events during your usage of Gullypro, the rules or terms and conditions for those events may indicate that your information will be shared with third parties with your consent. You are advised to review the applicable rules and/or terms and conditions for any promotions, surveys, questionnaires or events.</p>
<p>In the event that Gullypro is involved in a merger, acquisition, sale, bankruptcy, insolvency, reorganization, receivership, assignment for the benefit of creditors, or the application of laws or equitable principles affecting creditors' rights generally, or other change of control, there may be a disclosure of your personal information to another entity related to such event.</p>
<p>In the event ownership or control of the Gullypro Portal/Service is acquired by a new owner, your information may be transferred to the new owner as such a transfer may be necessary for the continued operation of the Gullypro Portal/Service. Any changes to this Privacy Policy by the new owner shall be notified on the Gullypro Portal.</p>
<p>This Portal (Gullypro) may use the Pollfish web plugin. Pollfish is an on-line survey platform, through which, anyone may conduct surveys. Pollfish collaborates with developers of applications for mobile phones (smart-phones) and website owners in order to have access to users of such applications/websites and address survey questionnaires to them. The Gullypro Portal/Service may enable the use of Pollfish cookies. When a user connects to Gullypro Portal/Service, Pollfish detects whether the user is eligible for a survey. Data collected by Pollfish shall be associated with your answers to the questionnaires whenever Pollfish sends such questionnaires to eligible users. The users of the Gullypro Portal/Service are requested to read the Pollfish respondent terms provided at&nbsp;<a href="https://www.pollfish.com/terms/respondent">https://www.pollfish.com/terms/respondent</a>.</p>
<p>By using and/or accessing the Gullypro Portal/Service you accept this Privacy Policy document and you hereby give your explicit consent for the placement of a Pollfish cookie in your system and the processing by Pollfish of the aforementioned data. Furthermore, you shall be given the option of disabling the Pollfish operation at any time by using the Pollfish &ldquo;opt out section&rdquo; available on Pollfish website or by disabling &ldquo;third party cookies&rdquo; from your browser&rsquo;s settings.</p>
<p>Monitoring Transactions &amp; Customer Support</p>
<p>All gaming and account transactions are recorded on our computer system. We also carry out routine monitoring of all transactions as they take place, to assist us in improving the service that we provide to you.</p>
<p>All telephone conversations from the Users to our Customer Support Centre may be recorded both to assist us in training and in quality management, and to allow for the speedy resolution of the queries.</p>
<p>All communications with Gullypro and its Customer Support shall be conducted in parliamentary language (language which is not offensive and/or abusive). Gullypro prevents and prohibits any such use of offensive and/or abusive language and strictest of actions shall be taken against the User who uses such offensive and/or abusive language including but not limited to suspension and/or termination of the User Account.</p>
<p>User&rsquo;s Choices</p>
<p>Gullypro will process your personal information in accordance with this Privacy Policy, and as part of that Gullypro provides you with certain choices about how we process your personal information. These choices are set out below.</p>
<p>You can access and update certain personal information Gullypro holds about you at any time by logging into your account via the Portal/Service. You can update your marketing preferences and whether or not you would like us to send you newsletters in your account. You can also unsubscribe to marketing emails and newsletters by using the 'unsubscribe' feature in the communication.</p>
<p>We may occasionally send display media to you, in a targeted way, whether through web or mobile browsers or mobile applications. You may opt out of many third parties that support and send this type of targeting advertising and you may learn more about this type of advertising in the below Section titled &ldquo;Third Party Advertising and Analytics.&rdquo; You may opt out of tracking for mobile advertising through the settings on most smartphones, and you may learn more about these settings through those mobile device platforms, such as Google (<a href="https://support.google.com/ads/answer/2662922?hl=en">https://support.google.com/ads/answer/2662922?hl=en</a>) and Apple (<a href="https://support.apple.com/en-in/ht202074">https://support.apple.com/en-in/ht202074</a>).</p>
<p>(Please note that these companies may either change the way these settings operate, the content or the availability of these pages).</p>
<p>We may occasionally send you push notifications to your mobile device. You can turn off certain push notifications in the account settings of your Gullypro Account. You can also turn off push notifications specific to our Portal/Service in the settings on your mobile device.</p>
<p>www.gullypro.com may also share information as provided by you and data concerning usage of the Amusement Facility and participation in the Games with third party service providers engaged by www.gullypro.com, for the purpose of data analytics or other similar purposes, for the purpose of storage, improving the services and helping gullypro serve you better.</p>
<p>Where we propose to use your personal information (that is, information that may be used to identify the User and that is not otherwise publicly available) for any other uses we will ensure that we notify you first. You will also be given the opportunity to withhold or withdraw your consent for your use other than as listed above.</p>
<p>By using the Portal, you hereby expressly agree and grant consent to the collection, use and storage of this information by www.gullypro.com. gullypro reserves the right to share, disclose and transfer information collected hereunder with its own affiliates. In the event gullypro sells or transfers all or a portion of its business assets, consumer information may be one of the business assets that are shared, disclosed or transferred as part of the transaction. You hereby expressly grant consent and permission to gullypro for disclosure and transfer of information to such third parties. Further, gullypro reserves the right to disclose personal information as obligated by law, in response to duly authorized legal process, governmental requests and as necessary to protect the rights and interests of&nbsp;<a href="https://www.apne11.com/">www.gullypro.com</a>.</p>
<p>Links:</p>
<p>www.gullypro.com also includes links to other websites. Such websites are governed by their respective privacy policies, which are beyond www.gullypro.com's control. Once the User leaves gullypro&rsquo;s servers (the User can tell where he/she is by checking the URL in the location bar on the User's browser), use of any information provided by the User is governed by the privacy policy of the operator of the site which the User is visiting. That policy may differ from gullypro&lsquo;s own. If the User can't find the privacy policy of any of these sites via a link from the site's homepage, the User may contact the site directly for more information. www.gullypro.com is not responsible for the privacy practices or the content of such websites.</p>
<p>Third Party Sharing, Advertising &amp; Analytics</p>
<p>Certain ads that may appear on our Portal/Service are delivered by our advertising partners. Our advertising partners may use cookies and other similar technologies, often in conjunction with unique (anonymous) cookie identifiers, to collect data about your activities and interests, including the technologies described above. Some of these partners may use mobile device identifiers, such as Apple IDFAs and Google/Android Advertising IDs. Doing this allows the ad companies to recognize your computer or device each time they send you an online or mobile advertisement. In this way, the ad companies may compile information about where you, or others who are using your computer or device, saw their advertisements and measure your interaction with each advertisement. This information allows advertisement companies to deliver targeted advertisements that may be of increased interest to you, both on our Portal/Service and elsewhere online. Just as these technologies may be used to target ads on our websites and apps, we, or our advertising partners, may use these same technologies and data points (e.g., mobile identifiers, cookie identifiers, location-based data), through our Portal/Service or through other services, to target advertising (for ourselves or other companies) on other sites or mobile apps. Sometimes, these identifiers may be derived from a hashed or encrypted version of personal information such as your email address. We may use this information to measure the performance of our advertising as well, for instance, to evaluate which ads or content our users prefer, or which are most effective. In addition, sometimes we or an advertising partner may tailor advertising to you across different devices.</p>
<p>Gullypro and/or www.gullypro.com may disclose the information it collects about the User to:</p>
<p>To its service providers, to its affiliates, sponsors, suppliers and others who help provide the Portal/Service to the User;</p>
<p>to licensors, activity and event partners and other third parties for their own marketing purposes, such as to provide information to the User about their new developments, special events, programs, services, activities, products, attractions, promotions and other important information;</p>
<p>Third parties to provide analytics or to confirm/update information provided by the User;</p>
<p>third parties in the event of any reorganization, merger, sale, joint venture, assignment, transfer or disposition of all or any portion of Gullypro business or other operations (including without limitation in connection with bankruptcy or any similar proceedings); and</p>
<p>Or as otherwise authorized by the User.</p>
<p>We may also share the User&rsquo;s personal information in response to a legal order or official request; when we believe the User has acted in violation of the Terms &amp; Conditions and/or Privacy Policy of Gullypro; to investigate, prevent or take action regarding suspected illegal activities, fraud or potential threats; to exercise legal rights or defend against claims; or as otherwise permitted or required by law.</p>
<p>We also may use, share or sell non-personally identifiable information with third parties. Additionally, we may take personally identifiable information and de-identify it and share it in a de-identified form with advertisers, business partners, and/or third parties in order to analyse usage of the services in order to improve our services and the User experience or for any similar purposes. Such data will not be re-identified and the contracting parties shall be asked to agree to keep the data in its de-identified form after such use.</p>
<p>If the User elects to participate in any promotions, surveys, questionnaires, or other events during his/her visit to Gullypro, the rules or terms and conditions for those events may indicate that the User&rsquo;s information will be shared with third parties with his/her consent. The Users are advised to review the applicable rules and/or terms and conditions for any promotions, surveys, questionnaires or events.</p>
<p>User Rights under this Privacy Policy</p>
<p>Right to withdraw consent</p>
<p>The User shall have the right to withdraw his or her consent at any time with respect to the processing and disclosure of the personal data/information provided to Gullypro.</p>
<p>Such withdrawal of consent shall not affect the lawfulness of any processing/disclosure based on User consent carried on by Gullypro before its withdrawal.</p>
<p>Right to Transparency and Communication</p>
<p>Gullypro shall take appropriate measures to provide any information referred to in this Privacy Policy and any communication under this Privacy Policy relating to processing to the User in a concise, transparent, intelligible and easily accessible form, using clear and plain language. Such information shall be provided in writing, or by other means, including, where appropriate, by electronic means. When requested by the User, the information may be provided orally, provided that the identity of the User is proven by other means.</p>
<p>Gullypro shall facilitate the exercise of User&rsquo;s rights under this Clause 9 and offer full co-operation and support towards the same.</p>
<p>Gullypro shall provide information on action taken on a request under this Clause 9 to the User without undue delay and in any event within two months of receipt of the request. That period may be extended by two further months where necessary, taking into account the complexity and number of the requests. Gullypro shall inform the User of any such extension within two months of receipt of the request, together with the reasons for the delay. Where the User makes the request by electronic form means, the information shall be provided by electronic means where possible, unless otherwise requested by the User.</p>
<p>Gullypro does not take action on the request of the User, Gullypro shall inform the User without delay and at the latest within one month of receipt of the request of the reasons for not taking action and on the possibility of lodging a complaint with a supervisory authority and seeking a judicial remedy.</p>
<p>Information provided under this Clause 9 and any communication and any actions taken under this Clause and Privacy Policy shall be provided free of charge. Where requests from a User are manifestly unfounded or excessive, in particular because of their repetitive character, Gullypro may either:</p>
<ol>
<li>charge a reasonable fee taking into account the administrative costs of providing the information or communication or taking the action requested;</li>
<li>refuse to act on the request. Gullypro shall bear the burden of demonstrating the manifestly unfounded or excessive character of the request.</li>
</ol>
<p>Without prejudice to this Clause, where Gullypro has reasonable doubts concerning the identity of the natural person making the request referred to herein, Gullypro may request the provision of additional information necessary to confirm the identity of the User.</p>
<p>Right to information</p>
<p>Where personal data relating to a User are collected from the User, Gullypro shall, at the time when personal data are obtained, provide the User with all of the following information:</p>
<ol>
<li>the identity and the contact details of Gullypro and, where applicable, of the Gullypro's representative;</li>
<li>the purposes of the processing for which the personal data are intended;</li>
<li>the recipients or categories of recipients of the personal data, if any;</li>
<li>categories of personal data concerned;</li>
<li>Where applicable, the fact that Gullypro intends to transfer personal data to a third party, third country or international organization.</li>
</ol>
<p>In addition to the information referred to in Clause 9.3.1, Gullypro shall, at the time when personal data are obtained, provide the User with the following further information necessary to ensure fair and transparent processing:</p>
<ul>
<li>The period for which the personal data will be stored, or if that is not possible, the criteria used to determine that period;</li>
<li>Where the processing is based or would be carried out;</li>
<li>The existence of the User&rsquo;s right to request from Gullypro access to and rectification or erasure of personal data or restriction of processing concerning the User or to object to processing;</li>
<li>The existence of the right to withdraw consent at any time, without affecting the lawfulness of processing based on consent before its withdrawal;</li>
<li>Whether the provision of personal data is a statutory or contractual requirement, or a requirement necessary to enter into a contract, as well as whether the User is obliged to provide the personal data and of the possible consequences of failure to provide such data.</li>
</ul>
<p>Where Gullypro intends to further process the personal data for a purpose other than that for which the personal data were collected, Gullypro shall provide the User, prior to that further processing, with information on that other purpose and with any relevant further information</p>
<p>The above stated provisions under Clauses 9.3.1, 9.3.2 and 9.3.3 shall also apply where Gullypro intends to collect information from the User.</p>
<p>Right to access to data</p>
<p>The User shall have the right to obtain from Gullypro confirmation as to whether or not personal data concerning him or her are being processed, and, where that is the case, access to the personal data and the following information:</p>
<ul>
<li>He purposes of the processing;</li>
<li>The categories of personal data concerned;</li>
<li>The recipients or categories of recipient to whom the personal data have been or will be disclosed, in particular recipients in third countries or international organizations;</li>
<li>Where possible, the envisaged period for which the personal data will be stored, or, if not possible, the criteria used to determine that period;</li>
<li>The existence of the right to request from Gullypro rectification or erasure of personal data or restriction of processing of personal data concerning the User or to object to such processing;</li>
<li>Where the personal data are not collected from the User, any available information as to their source;</li>
</ul>
<p>Where personal data are transferred to a third party, third country or to an international organisation, the User shall have the right to be informed of the appropriate safeguards implemented by Gullypro.</p>
<p>Upon request by the User, Gullypro shall provide a copy of the personal data undergoing processing. For any further copies requested by the User, Gullypro may charge a reasonable fee based on administrative costs. Where the User makes the request by electronic means, and unless otherwise requested by the User, the information shall be provided in a commonly used electronic form.</p>
<p>Right to rectification</p>
<p>The User shall have the right to obtain from Gullypro without undue delay the rectification of inaccurate personal data concerning him or her. Taking into account the purposes of the processing, the User shall have the right to have incomplete personal data completed, including by means of providing a supplementary statement.</p>
<p>Right to erasure (Right to be forgotten)</p>
<p>The User shall have the right to obtain from Gullypro the erasure of personal data concerning him or her without undue delay and Gullypro shall have the obligation to erase personal data without undue delay where one of the following grounds applies:</p>
<ol>
<li>the personal data are no longer necessary in relation to the purposes for which they were collected or otherwise processed;</li>
<li>the User withdraws consent on which the processing is based and where there is no other legal ground for the processing;</li>
<li>He personal data have to be erased for compliance with a legal obligation under any law to which Gullypro is subject.</li>
<li>the User objects to the processing pursuant to Clause 9.9 and there are no overriding legitimate grounds for the processing;</li>
<li>the personal data has been unlawfully processed;</li>
</ol>
<p>Where Gullypro has made the personal data public and is obliged pursuant to Clause 9.6.1 to erase the personal data, Gullypro, taking account of available technology and the cost of implementation, shall take reasonable steps, including technical measures, to inform entities which are processing the personal data that the User has requested the erasure by such entities of any links to, or copy or replication of, those personal data.</p>
<p>Sub-clauses 9.6.1 and 9.6.2 shall not apply to the extent that processing is necessary:</p>
<ol>
<li>for exercising the right of freedom of expression and information;</li>
<li>for compliance with a legal obligation which requires processing by any law to which Gullypro is subject or for the performance of a task carried out in the public interest or in the exercise of official authority vested in Gullypro;</li>
<li>For the establishment, exercise or defense of legal claims.</li>
</ol>
<p>Right to restriction of processing</p>
<p>The User shall have the right to obtain from Gullypro restriction of processing where one of the following applies:</p>
<ol>
<li>the accuracy of the personal data is contested by the User, for a period enabling Gullypro to verify the accuracy of the personal data;</li>
<li>the processing is unlawful and the User opposes the erasure of the personal data and requests the restriction</li>
<li>Gullypro no longer needs the personal data for the purposes of the processing, but they are required by the User for the establishment, exercise or defence of legal claims;</li>
<li>the User has objected to processing pursuant to Clause 9.9 pending the verification whether the legitimate grounds of Gullypro override those of the User.</li>
</ol>
<p>Where processing has been restricted under Sub Clause 9.7.1, such personal data shall, with the exception of storage, only be processed with the User's consent or for the establishment, exercise or defence of legal claims or for the protection of the rights.</p>
<p>Right to data portability</p>
<p>The User shall have the right to receive the personal data concerning him or her, which he or she has provided to Gullypro, in a structured, commonly used and machine-readable format and have the right to transmit those data to another entity/body without hindrance from Gullypro.</p>
<p>Right to object</p>
<p>The User shall have the right to object, on grounds relating to his or her particular situation, at any time to processing of personal data concerning him or her including profiling. Gullypro shall no longer process the personal data unless Gullypro demonstrates compelling legitimate grounds for the processing which override the interests, rights and freedoms of the User or for the establishment, exercise or defence of legal claims.</p>
<p>Where personal data are processed for direct marketing purposes, the User shall have the right to object at any time to processing of personal data concerning him or her for such marketing, which includes profiling to the extent that it is related to such direct marketing.</p>
<p>Where the User objects to processing for direct marketing purposes, the personal data shall no longer is processed for such purposes.</p>
<p>Users from Excluded Locations</p>
<p>The Excluded Location shall be defined as the Countries/regions other than Republic of India and Excluded States in India where the Games at Gullypro shall not be offered and accessed and/or prohibited to be offered and accessed by the users. Users are requested to peruse the Terms &amp; Conditions to see the meaning of &lsquo;Excluded States&rsquo;.</p>
<p>If you are a user accessing our Portal/Service from any Excluded locations (Excluded States in India and countries/regions other than Republic India) with laws or regulations governing personal data collection, use, and disclosure, your continued use of the Gullypro Portal/Service and facilities/services (governed by the Indian laws, Gullypro Terms &amp; Conditions and Privacy Policy) shall amount to your express and implied consent to the transfer of your personal information to Gullypro as per the laws and regulations of the Republic of India.</p>
<p>Information Security Procedures:</p>
<p>We are committed to protecting the security of your personal information. Protection of the User Information, including the registration details or any other payment information the User provides to us, is a priority for us. We use a variety of security technologies and procedures to help protect your personal information from unauthorized access, use, or disclosure.</p>
<p>Any personal information which identifies the User will be encrypted at all times whilst in transit over the internet. The technology used by us encrypts any information sent by the User on secured pages. Our server then reads the information using a private key. This means that your information, be it any payment information provided to us or any other personal details, is turned into a code that can only be decoded with the private key or password. All information gathered on the Portal is securely stored within a Gullypro controlled database. The database is stored on servers secured behind a firewall; access to such servers being password-protected and strictly limited based on need-to-know basis.</p>
<p>Whilst neither we, nor any other organization, can guarantee the security of information processed online, we do have appropriate security measures in place to protect your personal information. For example, we store the personal information you provide on computer systems with limited access that are located in facilities to which access is limited. However, we understand that as effective as our security measures are, no security system is impenetrable. Thus, we cannot guarantee the security of our database, nor can we guarantee that information you supply will not be intercepted while being transmitted to us over the Internet.</p>
<p>To further protect your privacy and security, we reserve the right to take reasonable steps (such as requesting your password) to verify your identity before granting you profile access or making corrections. We may periodically review from time to time and change our privacy policy to incorporate such future changes as may be considered appropriate, without any notice to you. Our use of any information we gather will always be consistent with the policy under which the information was collected, regardless of what the new policy may be. Any changes to our privacy policy will be posted on this page, so you are always aware of what information we collect, how we use it, how we store it and under what circumstances we disclose it.</p>
<p>Additionally, you should ensure your password is kept secret at all times. You will be responsible for maintaining the secrecy of your password and account information.</p>
<p>All information gathered on www.gullypro.com is securely stored within Www.gullypro.com- controlled database. The database is stored on servers secured behind a firewall; access to such servers being password-protected and strictly limited based on need-to-know basis. However, we understand that as effective as our security measures are, no security system is impenetrable. Thus, we cannot guarantee the security of our database, nor can we guarantee that information you supply will not be intercepted while being transmitted to us over the Internet. Further, any information you include in a posting to the discussion areas will be available to anyone with Internet access. By using the Portal, you understand and agree that your information may be used in or transferred to countries other than India.</p>
<p>gullypro also believes that the internet is an ever-evolving medium. We may periodically review from time to time and change our privacy policy to incorporate such future changes as may be considered appropriate, without any notice to you. Our use of any information we gather will always be consistent with the policy under which the information was collected, regardless of what the new policy may be. Any changes to our privacy policy will be posted on this page, so you are always aware of what information we collect, how we use it, how we store it and under what circumstances we disclose it.</p>
<p>Advertising:</p>
<p>When www.gullypro.com presents information to it's online advertisers -- to help them understand our audience and confirm the value of advertising on the Portal -- it is usually in the form of aggregated statistics on traffic to various pages within our site. When you register with www.gullypro.com, we contact you from time to time about updating your content to provide features which we believe may benefit you.</p>
<p>Several deceptive emails, websites, blogs etc. claiming to be from or associated with www.gullypro.com may or are circulating on the Internet. These emails, websites, blogs etc. often include our logo, photos, links, content or other information. Some emails, websites, blogs etc. call the user to provide login name, password etc. or that the user has won a prize/ gift or provide a method to commit illegal/ unauthorized act or deed or request detailed personal information or a payment of some kind. The sources and contents of these emails, websites, blogs etc. and accompanying materials are in no way associated with www.gullypro.com. For your own protection, we strongly recommend not responding to emails or using websites, blogs etc. We may use the information provided by you to www.gullypro.com, including your email address or phone number, to contact you about the Amusement Facilities or other services availed by you or to inform you of our Amusement Facilities and services.</p>
<p>Unsubscribing to Communications:</p>
<p>If the User does not want to receive any e-mails from us in the future, they are required to let us know by dropping an email to us. We will use our reasonable endeavours to remove the User&rsquo;s name from the related mailing list within 14 working days of his/her request. The User may also change his/her preferences at any time by revising his/her account profile by un-ticking the boxes for the previously opted communications.</p>
<p>The User may also click the &ldquo;unsubscribe&rdquo; link (if present) at the bottom of any emails he/she may receive from us and follow the necessary instructions provided.</p>
<p>Privacy Measures for Minors:</p>
<p>Gullypro is intended for persons who are 18 years of age or above. If the User is under 18 years of age, he/she shall not be permitted to use the platform &lsquo;Gullypro&rsquo;</p>
<p>If the User is a parent and/or guardian and believe that we may have inadvertently collected personal information from their child, they can notify us immediately by sending an email to&nbsp;<a href="mailto:info@apne11.com">info@gullypro.com</a>.</p>
<p>Conditions of Use:</p>
<p>www.gullypro.com, Gullypro and/or https://www.gullypro.com DOES NOT WARRANT THAT THIS PORTAL, IT&rsquo;S SERVERS, OR EMAIL SENT BY US OR ON OUR BEHALF ARE VIRUS FREE. www.gullypro.com Gullypro and/or https://www.gullypro.com WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THIS PORTAL, INCLUDING, BUT NOT LIMITED TO COMPENSATORY, DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, SPECIAL AND CONSEQUENTIAL DAMAGES, LOSS OF DATA, GOODWILL, BUSINESS OPPORTUNITY, INCOME OR PROFIT, LOSS OF OR DAMAGE TO PROPERTY AND CLAIMS OF THIRD PARTIES. IN NO EVENT WILL www.gullypro.com, Gullypro and/or https://www.gullypro.com BE LIABLE FOR ANY DAMAGES WHATSOEVER IN AN AMOUNT IN EXCESS OF AN AMOUNT OF INR 100</p>
<p>Retention of Data:</p>
<p>Your personal information may be retained and may continue to be used until:</p>
<ol>
<li>the relevant purposes for the use of your information described in this Privacy Policy are no longer applicable; and</li>
<li>we are no longer required by applicable law, regulations, contractual obligations or legitimate business purposes to retain your personal information and the retention of your personal information is not required for the establishment, exercise or defense of any legal claim.</li>
</ol>
<p>Applicable Law and Jurisdiction:</p>
<p>Gullypro is created and controlled by Mindsarray Network Pvt Ltd in India. As such, the laws of India will govern these Terms &amp; Conditions and Privacy Policy.</p>
<p>The User hereby irrevocably and unconditionally consents to submit all disputes pertaining to these Terms &amp; Conditions and Privacy Policy to the exclusive jurisdiction of a sole arbitrator appointed as per the Arbitration and Conciliation Act 1996, as amended from time to time. The seat of arbitration shall be Delhi and the language of the proceedings shall be English.</p>
<p>By visiting this Portal, you agree that the laws of the Republic of India without regard to its conflict of laws principles, govern this Privacy Policy and any dispute arising in respect hereof shall be subject to and governed by the dispute resolution process set out in the Terms and Conditions (https://www.gullypro.com/terms.html).</p>
<p>Language:</p>
<p>All communications between the User and Gullypro, wwww.gullypro.com, and/or any other entity of Gullypro shall be communicated in written form vide Electronic Mail (E-Mail) and in either English or Hindi language. Further, all communications between the User and the Customer Support shall also be conducted in either English or Hindi language.</p>
<p>Updating Information:</p>
<p>This Privacy Policy may be revised periodically, and this will be reflected by the "Last update posted" date above. Please revisit this page to stay aware of any changes. If a revision to this Privacy Policy, in our sole discretion, is material, we will notify you by contacting you through the email address associated with your account.</p>
<p>You will promptly notify www.gullypro.comGullypro if there are any changes, updates or modifications to your information. Further, you may also review, update or modify your information and user preferences by logging into your Profile page on the Portal.</p>
<p>You will promptly notify www.gullypro.comGullypro if there are any changes, updates or modifications to your information. Further, you may also review, update or modify your information and user preferences by logging into your Profile page on the Portal.</p>
<p>Contact Us:</p>
<p>Contact Information:&nbsp;Any questions or clarifications with respect to this Policy or any complaints, comments, concerns or feedback can be sent to <a href="http://www.gullypro.com">www.gullypro.com</a></p>
<p>&nbsp;at:&nbsp;<a href="mailto:supports@gullypro.com">supports@gullypro.com</a>&nbsp;or by normal/physical mail addressed to:</p>
<p>Attn:&nbsp;www.gullypro.com Team</p>
<p>Address-Malad East</p>
<p><br />User is responsible for keeping his/her information current. The User may update his/her information by contacting us at&nbsp;<a href="mailto:support@gullypro.com">support@gullypro.com</a>&nbsp;and we will use reasonable efforts to process any change the User makes; provided, however, that requests to delete information are subject to our internal reporting, processing and retention policies and all applicable legal obligations.</p>
                </div>
            </div>
        )
    }
}

export default Legality
