import React, { Component } from 'react'
import Header from '../common/Header/Header';
import './staticPages.scss';

export class termsandcondition extends Component {
    render() {
        let fields = {
            title: 'Terms & Condition', 
            sideToggle: false,
            crossButton: {
                showFlag: false,
            },
            backButton: {
                showFlag: true,
                url: 'goback',
            },
            styleCss:{
                background: '#FFFFFF', 
                text: '#000000'
            }, 
            'points': false, 
            'wallet': false
        };
        return (
            <div>
                <Header fields={fields} />
                <div className ='static-content content col-12'>
                    <p><span style={{fontWeight: 400}}>By subscribing/registering to/on or using https://www.gullypro.com/, its sub-domains and/or Gullypro Web (web application accessible through a mobile phone or a tablet device) collectively referred to “Gullypro site” and/or any services provided on the Gullypro site, you agree that you have read, understood and have agreed to be bound by these Terms and Conditions, regardless of how you subscribe to or use these services. If you do not want to be bound by these Terms and Conditions, you must not subscribe to or register or use the Gullypro site or any of its services.</span></p>
                    <p><span style={{fontWeight: 400}}>For the purpose of these Terms and Conditions, wherever the context so require&nbsp;"you"&nbsp;or&nbsp;"your"&nbsp;or&nbsp;"User"&nbsp;or&nbsp;“Participant”&nbsp;shall mean any natural or legal person who has agreed to become a member of the Gullypro site by registering on the Gullypro site as registered User or a person who has used the Gullypro site either through browsing or otherwise. Your access or use of the Gullypro site is subject to the Terms and Conditions as set out herein (“Terms and Conditions”) and the Privacy Policy made available at the Gullypro site.&nbsp;“We”,&nbsp;“us”,&nbsp;“our”, “Gullypro” shall mean “Company Name”and/or any of its affiliated entities.</span></p>
                    <p><span style={{fontWeight: 400}}>GULLYPRO SERVICE</span></p>
                    <p><span style={{fontWeight: 400}}>Gullypro shall be entitled to modify these Terms and Conditions and the rules governing its games/tournaments/contests, at any time, by posting the same on Gullypro site. Use of Gullypro constitutes your acceptance of such Terms and Conditions and the rules referred to herein or provided by Gullypro in relation to any Gullypro services, as may be amended from time to time. You may then exercise the options provided in such a notification to indicate non-acceptance of the modified Terms and Conditions and/or the rules. If such an option is not exercised by you within the time frame prescribed in the notification, you will be deemed to have accepted the modified Terms and Conditions and/or the rules provided by Gullypro.</span></p>
                    <p><span style={{fontWeight: 400}}>Gullypro site may contain links to third party websites that are not owned or controlled by Gullypro. Gullypro has no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party websites/app. In addition, Gullypro will not and cannot censor or edit the content of any third-party site. By using the Gullypro site and its services, you expressly acknowledge and agree that Gullypro shall not be responsible for any damages, claims or other liability arising from or related to your use of any third-party website.</span></p>
                    <p><span style={{fontWeight: 400}}>USER REGISTRATION</span></p>
                    <p><span style={{fontWeight: 400}}>You may use the Gullypro site without registration. However, to participate in the activities of the Gullypro site you shall be required to create an account by logging in through your Google account, Facebook account or any other third-party service account permitted by the Gullypro site. In the event you wish to play on the Gullypro site you shall create an account with us. You shall do so after completing the registration process by:</span></p>
                    <p><span style={{fontWeight: 400}}>(a). Providing true, accurate, correct and complete information as prompted by the applicable registration form.</span></p>
                    <p><span style={{fontWeight: 400}}>(b). Maintaining and updating true, accurate, correct and complete information provided by you during the registration process.</span></p>
                    <p><span style={{fontWeight: 400}}>You shall be required to choose a username and password. You shall be solely responsible for maintaining the confidentiality of your account username and password.</span></p>
                    <p><span style={{fontWeight: 400}}>You shall be solely responsible for the registration information provided by you during submissions and the consequences of posting or publishing them. Gullypro is only acting as a repository of data and makes no guarantee as to the validity, accuracy, or legal status of any information / submissions.</span></p>
                    <p><span style={{fontWeight: 400}}>If, at any time, Gullypro believes that your account and password is being misused in any manner, or that the information provided by you during the above stated registration process is not true, inaccurate or incomplete, then Gullypro reserves the right to terminate/cancel or suspend your account and block your access to the Gullypro site.</span></p>
                    <p><span style={{fontWeight: 400}}>You shall be solely and exclusively responsible for any and/or all the activities that are carried through your account. You agree to notify Gullypro of any unauthorized use of your account and/or any breach of security via email at info@gullypro.com. Gullypro shall not be liable for any loss that you may incur as a result of another person(s) using your account username and/or password and/or your failure to comply with this section. You shall be solely and exclusively liable for all the losses to Gullypro and/or other claims, damages, fines due to such unauthorized use.</span></p>
                    <p><span style={{fontWeight: 400}}>If Gullypro charges you a platform fee (facilitation fee) in respect of any Gullypro services, Gullypro shall, without delay, refund such platform fee in the event of suspension and/or termination of your account or Gullypro services on account of any fault on the part of Gullypro. It is hereby clarified that no refund shall be payable if such suspension and/or termination is affected due to any breach or failure to adhere to any of these Terms and Conditions, Privacy Policy and/or any other rules by the you, the User, or a person(s) accessing your account by using your username and password; or any circumstances beyond the reasonable control of Gullypro.</span></p>
                    <p><span style={{fontWeight: 400}}>REGISTRATION AND PARTICIPANTS</span></p>
                    <p><span style={{fontWeight: 400}}>The games/tournaments/contests available on the Gullypro site are open only to residents of India except the States of Assam, Odisha (Orissa), Telangana and Nagaland (“Excluded States”) aged eighteen (18) years or above at the date of usage and/or registration. Employees of Mindsarray Network Private Limited (Gullypro), their associated, affiliated and subsidiary companies and their families, agents, game sponsors, and any person connected with Gullypro are excluded from participating in the game and/or winning a prize. By taking part in a game (excluding administering the game) on the Gullypro site, Users/Participants warrant that all information submitted by them is true, accurate and complete. Proof of age shallmay be required. The sole discretion to declare a User ineligible to participate shall vest with Gullypro. Users/Participants who wish to participate shall have a valid email address. In order to register for the games/tournaments/contestsContest(s), Users/Participants are required to accurately provide the following information:</span></p>
                    <ul>
                    <li style={{fontWeight: 400}}><span style={{fontWeight: 400}}>Full Name</span></li>
                    <li style={{fontWeight: 400}}><span style={{fontWeight: 400}}>Team Name(s)</span></li>
                    <li style={{fontWeight: 400}}><span style={{fontWeight: 400}}>E-mail address</span></li>
                    <li style={{fontWeight: 400}}><span style={{fontWeight: 400}}>Password</span></li>
                    <li style={{fontWeight: 400}}><span style={{fontWeight: 400}}>State of Residence</span></li>
                    <li style={{fontWeight: 400}}><span style={{fontWeight: 400}}>Gender</span></li>
                    <li style={{fontWeight: 400}}><span style={{fontWeight: 400}}>Date of Birth</span></li>
                    </ul>
                    <p>&nbsp;</p>
                    <p><span style={{fontWeight: 400}}>USE OF GULLYPRO SITE</span></p>
                    <p><span style={{fontWeight: 400}}>All materials provided on the Gullypro site, including but not limited to all information, materials, functions, text, logos, designs, graphics, images, sounds, software, documents, products and services (collectively, the "Materials"), and the selection, arrangement and display thereof, are the copyrighted works of Gullypro and/or its vendors and/or suppliers. All Materials herein and Gullypro’s software are the exclusive properties of Gullypro. Except as stated herein, none of the Materials may be modified, copied, reproduced, distributed, republished, downloaded, displayed, sold, compiled, posted or transmitted in any form or by any means, including but not limited to, electronic, mechanical, photocopying, recording or other means, without the prior written permission of Gullypro.</span></p>
                    <p><span style={{fontWeight: 400}}>Subject to your compliance with these Terms and Conditions, Gullypro hereby grants you the right to access and use the Gullypro site only for personal and non-commercial purposes. You undertake that you shall not use the Gullypro site for any commercial purposes and/or in any way that is unlawful, or harms us or any other person or entity, as determined in our sole discretion.</span></p>
                    <p><span style={{fontWeight: 400}}>You may post/share links/images/text content on the Gullypro site on social media platforms like Facebook, Twitter, Google+, Snapchat, Instagram, YouTube or any other social media sharing platform with appropriate link-back to the original source.</span></p>
                    <p><span style={{fontWeight: 400}}>When the Gullypro site provides for the download of any particular Material including any software, you may download such Material and/or software to a computer or mobile device (as web applicable) for your personal, non-commercial use only, provided that you shall:</span></p>
                    <p><span style={{fontWeight: 400}}>(a). keep a record of and not amend copyright and other proprietary notices;</span></p>
                    <p><span style={{fontWeight: 400}}>(b). make no modifications to, and do not rent, lease, loan, sell, distribute, copy (except to create a single copy for your own back-up purposes), or create any derivative works based on the Gullypro site or the Material including the software, in whole or in part, and;</span></p>
                    <p><span style={{fontWeight: 400}}>(c). not transfer any Material and/or software and/or any part thereof to any other computer and/or mobile device. Any commercial or business use of the Gullypro site or any Material including the software is expressly prohibited.</span></p>
                    <p><span style={{fontWeight: 400}}>You acknowledge and agree that nothing in these Terms and Conditions shall have the effect of transferring the ownership of any copyrights, trademarks, service marks, trade names, source code or other proprietary rights on the Gullypro site or Material or software or any part thereof to you or any third party.</span></p>
                    <p><span style={{fontWeight: 400}}>FAIR PLAY POLICY AND PROHIBITED USE</span></p>
                    <p><span style={{fontWeight: 400}}>5.1 Fair Play Policy</span></p>
                    <p><span style={{fontWeight: 400}}>We at Gullypro consider the fair play of online fantasy game/tournament/contest of utmost importance. In order to prevent any form of fraud or unfair play in our games/contests/tournaments or on our site - all User actions including - deposits/identity verification/Fantasy Games/Tournaments/Contests are monitored to ensure a safe, legal and fair environment for you (the Users/Participants).</span></p>
                    <p><span style={{fontWeight: 400}}>Every single fantasy game/tournament/contest shall be a fair individual effort. Hence, as part of the Fair Play policy to prevent any forms of fraud &amp; in-game collusion all User/Participant actions are monitored and recorded.</span></p>
                    <p><span style={{fontWeight: 400}}>Any detection of a breach of our Fair Play policy, such as and not limited to, fraudulent deposits under a stolen identity or collusion in gameplay, shall result in swift and serious action taken by Gullypro against the suspected User/Participant.</span></p>
                    <p><span style={{fontWeight: 400}}>5.2 Prohibited Use</span></p>
                    <p><span style={{fontWeight: 400}}>As a condition of your use of the Gullypro site, you shall not use the Gullypro site for any purpose that is unlawful or prohibited under these Terms and Conditions and/or under any Indian laws, statutes, order, ordinances and regulations. The duty to verify whether the use of the Gullypro site is legal in your jurisdiction is your sole and exclusive responsibility.</span></p>
                    <p><span style={{fontWeight: 400}}>You shall not display, upload, modify, publish, transmit, update or share any information on the Gullypro site that is:</span></p>
                    <ol>
                    <li><span style={{fontWeight: 400}}> criminal or tortious activity, including child pornography, fraud including financial fraud and money laundering, trafficking in obscene material, drug dealing, gambling, harassment, stalking, spamming, spimming, sending of viruses or other harmful files, copyright infringement, patent infringement, or theft of trade secrets;</span></li>
                    <li><span style={{fontWeight: 400}}> Promoting illegal or tortuous activities or conduct that is abusive, threatening, obscene, defamatory or libellous;</span></li>
                    </ol>
                    <p><span style={{fontWeight: 400}}>iii. using photos and/or pictures that are sexually explicit or pornographic, exposing the female breast or full exposure of either male or female buttocks, or any or all portions of the human genitalia; exposing anyone or anything involved in explicit sexual acts and/or lewd and lascivious behaviour, including masturbation, copulation, paedophilia, intimacy involving nude or partially nude people in heterosexual, bisexual, lesbian, or homosexual encounters; depicting anyone or anything that is crudely vulgar or grossly deficient in civility or behaviour or that shows scatological impropriety and any other content contravening good moral standards;</span></p>
                    <ol>
                    <li><span style={{fontWeight: 400}}> attempting to circumvent, disable or otherwise interfere with security-related features of Gullypro or features that prevent or restrict use or copying of any content or enforce limitations on the use of Gullypro or the content therein;</span></li>
                    <li><span style={{fontWeight: 400}}> using cheats, exploits, automation software, bots, hacks, mods or any other unauthorized software designed to modify or interfere with the Gullypro site, and taking advantage of cheats or exploits;</span></li>
                    <li><span style={{fontWeight: 400}}> Using any software that intercepts, mines, or otherwise collect information about other Users or copies and stores any Proprietary Materials;</span></li>
                    </ol>
                    <p><span style={{fontWeight: 400}}>vii. Interfering with, disrupting, or creating an undue burden on the Gullypro site or the networks connected to the Gullypro site;</span></p>
                    <p><span style={{fontWeight: 400}}>viii. Attempting to impersonate another User or person;</span></p>
                    <ol>
                    <li><span style={{fontWeight: 400}}> Soliciting personal information from anyone under eighteen (18) years of age;</span></li>
                    <li><span style={{fontWeight: 400}}> collecting, harvesting, soliciting or posting passwords or personally identifiable information from other Users;</span></li>
                    <li><span style={{fontWeight: 400}}> Using the account, username, or password of another account holder at any time or disclosing the User account password to any third party or permitting any third party to access the User Account;</span></li>
                    </ol>
                    <p><span style={{fontWeight: 400}}>xii. Using any information obtained from the Gullypro site in order to harass, abuse, or harm another person;</span></p>
                    <p><span style={{fontWeight: 400}}>xiii. Using any unfair, misleading or deceptive content intended to draw traffic to one’s profile;</span></p>
                    <p><span style={{fontWeight: 400}}>xiv. Using the Gullypro site and/or software in a manner inconsistent with any and all applicable laws and regulations;</span></p>
                    <ol>
                    <li><span style={{fontWeight: 400}}> sub-license, rent, lease, sell, trade, gift, bequeath or other transfer of the User account associated with the User account to anyone;</span></li>
                    </ol>
                    <p><span style={{fontWeight: 400}}>xvi. access or use of a third-party account that have been sub-licensed, rented, leased, sold, traded, gifted, bequeathed, or otherwise transferred from the holder or the original account creator; and</span></p>
                    <p><span style={{fontWeight: 400}}>xvii. using the Gullypro site and/or Software and/or materials for commercial purpose manner.</span></p>
                    <p><span style={{fontWeight: 400}}>LEGALITY</span></p>
                    <p><span style={{fontWeight: 400}}>The Legality of the Gullypro Site shall be available at&nbsp;</span><a href="https://www.apne11.com/legality.html"><span style={{fontWeight: 400}}>Legality</span></a></p>
                    <p><span style={{fontWeight: 400}}>INTERNATIONAL USERS</span></p>
                    <p><span style={{fontWeight: 400}}>The Gullypro site and services are hosted in the Republic of India and are intended for and directed to Users/Participants in the Republic of India (except the Excluded States). Gullypro makes no representation that the Gullypro site is appropriate or available in locations outside India. Those who choose to access the Gullypro site from outside India and/or the Excluded States are doing it at their own risk and shall be themselves responsible for compliance with the applicable laws.</span></p>
                    <p><span style={{fontWeight: 400}}>If you are a User/Participant accessing the Gullypro site and service from any region with laws or regulations governing personal data collection, use, and disclosure, your continued use of Gullypro site and service (governed by the Indian laws, Gullypro Terms &amp; Conditions and Privacy Policy) you consent to transfer your personal information to Gullypro as per the Republic of India laws and regulations applicable at that time.</span></p>
                    <p><span style={{fontWeight: 400}}>USER CONDUCT</span></p>
                    <p><span style={{fontWeight: 400}}>You agree to abide by these Terms and Conditions and all other rules, regulations of the Gullypro site. In the event you do not abide by these Terms and Conditions and all other rules, regulations, Gullypro may, at its sole and exclusive discretion, take necessary remedial action, including but not limited to:</span></p>
                    <p><span style={{fontWeight: 400}}>Restricting, suspending, or terminating your access to all or any part of Gullypro services;</span></p>
                    <p><span style={{fontWeight: 400}}>Deactivating or deleting your account and all related information and files on the account. Any winnings amount on the date of deactivation or deletion shall be transferred to the User account in Gullypro database subject to a processing fee (if any) applicable on such transfers as set out herein; or</span></p>
                    <p><span style={{fontWeight: 400}}>Refraining from awarding any prize(s) to such User.</span></p>
                    <p><span style={{fontWeight: 400}}>You agree to provide true, accurate, current and complete information at the time of registration and at all other times (as required by Gullypro). You further agree to update and keep updated your registration information as and when required by Gullypro.</span></p>
                    <p><span style={{fontWeight: 400}}>You shall not register or operate more than one User account with Gullypro.</span></p>
                    <p><span style={{fontWeight: 400}}>You shall provide all the necessary Mandatory Information Documents (MIDs) (referred to in Clause 15 of these Terms and Conditions) as and when required by Gullypro as per compliance of the Republic of India laws and regulations.</span></p>
                    <p><span style={{fontWeight: 400}}>You agree to ensure that you can receive all communications from Gullypro by marking emails from Gullypro as part of your "safe senders" list. Gullypro shall not be held liable if any email remains unread as a result of such an email being delivered to your junk and/or spam folder.</span></p>
                    <p><span style={{fontWeight: 400}}>Any password issued by Gullypro to you shall not be revealed to anyone else. You shall strictly avoid using any other user’sanyone else's password. You shall be responsible for maintaining the confidentiality of your account and password. You agree to immediately notify Gullypro of any unauthorized use of your account or any other breach of security.</span></p>
                    <p><span style={{fontWeight: 400}}>You agree to exit/log-out of your accounts at the end of each session. Gullypro shall not be responsible for any loss and/or damage that may result if you fail to comply with these requirements.</span></p>
                    <p><span style={{fontWeight: 400}}>You agree not to use cheats, exploits, automation, software, bots, hacks or any unauthorised third party software designed to modify or interfere with Gullypro services and/or Gullypro experience or assist in such activity.</span></p>
                    <p><span style={{fontWeight: 400}}>You agree not to copy, modify, rent, lease, loan, sell, assign, distribute, reverse engineer, grant a security interest in, or otherwise transfer any right to the technology or software underlying Gullypro or Gullypro services.</span></p>
                    <p><span style={{fontWeight: 400}}>You agree that without Gullypro’s express written consent, you shall not modify or cause to modify any files or software that are a part of Gullypro’s services.</span></p>
                    <p><span style={{fontWeight: 400}}>You agree that you shall not indulge in collusive play with other Users/Participants on the Gullypro site in any manner.</span></p>
                    <p><span style={{fontWeight: 400}}>You agree not to disrupt, overburden, or aid or assist in the disruption or overburdening of (a) any computer or server used to offer or support Gullypro or the Gullypro services (each a "Server"); or (b) enjoyment of the Gullypro services by any other User/Participant or person.</span></p>
                    <p><span style={{fontWeight: 400}}>You agree not to institute, assist or become involved in any type of attack, including without limitation to the distribution of a virus, denial of service, or other attempts to disrupt the Gullypro services or any other person's use or enjoyment of the Gullypro services.</span></p>
                    <p><span style={{fontWeight: 400}}>You shall not attempt to gain unauthorised access to the User accounts, servers or networks connected to the Gullypro services by any means other than the User interface provided by Gullypro, including but not limited to, by circumventing or modifying, attempting to circumvent or modify, or encouraging or assisting any other person to circumvent or modify, any security, technology, device, or software that is part of the Gullypro services.</span></p>
                    <p><span style={{fontWeight: 400}}>If you choose a username that, in Gullypro’s opinion is considered to be obscene, indecent, abusive or that might subject Gullypro and/or Mindsarray Network Private Limited to public disparagement or scorn, Gullypro/Mindsarray Network Private Limited reserves the right, without prior notice, to change such username and intimate you or delete such username from Gullypro, deny you access to Gullypro, or any combination of these options.</span></p>
                    <p><span style={{fontWeight: 400}}>Unauthorized access to the Gullypro site shall be considered a breach of these Terms and Conditions, Privacy Policy and a violation of the applicable Republic of India laws and regulations. You agree not to access the Gullypro site by any means other than through the interface that is provided by Gullypro for use in accessing the Gullypro site. You agree not to use any automated means, including, without limitation, agents, robots, scripts, or spiders, to access, monitor, or copy any part of our site, except those that has been approved in advance and in writing by us.</span></p>
                    <p><span style={{fontWeight: 400}}>Use of the Gullypro site shall be subject to existing Republic of India laws &amp; regulations and legal processes. Nothing contained in these Terms and Conditions, shall limit Gullypro’s right to comply with governmental, court, and law- enforcement requests or requirements relating to User’s use of Gullypro.</span></p>
                    <p><span style={{fontWeight: 400}}>Users may contact supports@gullypro.com with problems or questions, as appropriate.</span></p>
                    <p><span style={{fontWeight: 400}}>Users agree not to institute, assist or become involved in any type of attack, including without limitation to distribution of a virus, denial of service, or other attempts to disrupt the Gullypro Services or any other person's use or enjoyment of the Gullypro Services.</span></p>
                    <p><span style={{fontWeight: 400}}>Users shall not attempt to gain unauthorised access to other User accounts on Gullypro by any means, including but not limited to, by circumventing or modifying, attempting to circumvent or modify, or encouraging or assisting any other person to circumvent or modify, any security, technology, device, or software that underlies or is part of the Gullypro services.</span></p>
                    <p><span style={{fontWeight: 400}}>Users provide their acceptance for not using the Gullypro platform for any sort of inadequate activities including (but not limited to): to engage in any obscene, offensive, indecent, racial, communal, anti-national, objectionable, defamatory or abusive action or communication; to harass, stalk, threaten, or otherwise violate any legal rights of other individuals; to transmit files that contain viruses, corrupted files, or any other similar software or programs that may damage or adversely affect the operation of another person's computer, gullypro.com, any software, hardware, or telecommunications equipment; to advertise, offer or sell any goods or services for any commercial purpose on gullypro.com without written consent of Gullypro; to Transmit content regarding services, products, surveys, contests, pyramid schemes, spam, unsolicited advertising or promotional materials, or chain letters.</span></p>
                    <p><span style={{fontWeight: 400}}>PARTICIPATION IN GAMES/TOURNAMENTS/CONTESTS</span></p>
                    <p><span style={{fontWeight: 400}}>By entering a games/tournaments/contestsContest, User/Participant agrees to be bound by these Terms and the decisions of Gullypro. Subject to the terms and conditions stipulated herein below, the Company, at its sole discretion, may disqualify any User/Participant from a game/tournament/contest, refuse to award benefits or prizes and require the return of any prizes, if the User engages in unfair conduct, which the Company deems to be improper, unfair or otherwise adverse to the operation of the games/tournaments/contests or is in any way detrimental to other Users/Participants which includes, but is not limited to:</span></p>
                    <p><span style={{fontWeight: 400}}>(i). Falsifying ones’ own personal information (including, but not limited to, name, email address, bank account details and/or any other information or documentation as may be requested by Gullypro to enter a contest and/or claim a prize/winning;</span></p>
                    <p><span style={{fontWeight: 400}}>(ii). Engaging in any type of financial fraud or misrepresentation including unauthorized use of credit/debit instruments, payment wallet accounts etc. to enter a game/tournament/contest or claim a prize. It is expressly clarified that the onus to prove otherwise shall solely lie on the User;</span></p>
                    <p><span style={{fontWeight: 400}}>(iii). Colluding with any other User(s) / Participant(s) or engaging in any type of syndicate play;</span></p>
                    <p><span style={{fontWeight: 400}}>(iv). Any violation of game/tournament/contest rules or the Terms and Conditions;</span></p>
                    <p><span style={{fontWeight: 400}}>(v). Accumulating points or prizes through unauthorized methods such as automated bots, or other automated means;</span></p>
                    <p><span style={{fontWeight: 400}}>(vi). Using automated means (including but not limited to harvesting bots, robots, parser, spiders or screen scrapers) to obtain, collect or access any information on the Website or of any User/Participant for any purpose;</span></p>
                    <p><span style={{fontWeight: 400}}>(vii). Tampering with the administration of a game/tournament/contest or trying to in any way tamper with the computer programs or any security measure associated with a game/tournament/contest;</span></p>
                    <p><span style={{fontWeight: 400}}>(viii). Obtaining other Users’/Participants’ information without their express consent and/or knowledge and/or spamming other Users/Participants (Spamming may include but shall not be limited to send unsolicited emails to Users/Participants, sending bulk emails to Gullypro Users/Participants, sending unwarranted email content either to selected Users/Participants or in bulk); or</span></p>
                    <p><span style={{fontWeight: 400}}>(ix). Abusing the Website in any way.</span></p>
                    <p><span style={{fontWeight: 400}}>It is clarified that in case a User/Participant is found to be in violation of this policy, Gullypro reserves its right to initiate appropriate Civil/Criminal remedies as it may be advised other than forfeiture and/or recovery of prize money if any.</span></p>
                    <p><span style={{fontWeight: 400}}>CONTEST(S) AND PRIZES</span></p>
                    <p><span style={{fontWeight: 400}}>As part of its Site, Gullypro may also conduct contest(s). Individual users wishing to participate game/tournament/contest on the Gullypro Site ("Participants") are invited to create their own fantasy teams ("Team/s") consisting of real-life cricketers (as applicable) involved in a real-life cricket (as applicable), series or tournament (each a "Sport Event") to which the fantasy game relates. Gullypro offers Participants fantasy game game/tournament/contest relating to Sport Events, and Participants can participate in such game/tournament/contest(s) with their Teams. Teams are awarded points on the basis of the real-life cricketers' (as applicable) performances at the end of a designated match, round or tournament of the game/tournament/contest(s). The Participant(s) whose Team(s) have achieved the highest aggregate score(s) in the game/tournament/contest shall be declared winners ("Winners"). In certain pre-specified game/tournament/contest(s), Gullypro may declare more than one Winner and distribute prizes to such Winners in increasing order of their Team's aggregate score at the end of the designated round(s) of the game/tournament/contest(s).</span></p>
                    <p><span style={{fontWeight: 400}}>The game/tournament/Contest(s) across the Site shall, in addition to the Terms and Conditions, rules and regulations mentioned herein, be governed by:</span></p>
                    <p><span style={{fontWeight: 400}}>"Fantasy Rules" available at “How To Play - Fantasy Cricket” and other rules and regulations (including rules and regulations in relation to any payments made to participate in the game/tournament/Contest(s)) and all Participants agree to abide by the same.</span></p>
                    <p><span style={{fontWeight: 400}}>There are paid versions of the game/tournament/Contest(s) made available by Gullypro. Users may participate in the game/tournament/Contest(s) by paying the pre-designated amount as provided on the relevant game/tournament/Contest page. The Participant with the highest aggregate points at the end of the predetermined round shall be eligible to win a pre-designated prize, as stated on the relevant game/tournament/Contest(s) page.</span></p>
                    <p><span style={{fontWeight: 400}}>A Participant may create different Teams for participation in game/tournament/Contest(s) offered in relation to a Sport Event across the Gullypro Site. However, unless Gullypro specifies otherwise in relation to any game/tournament/Contest ("Multiple Entry Contest"), Participants acknowledge and agree that they may enter only one Team in any game/tournament/Contest offered in relation to a Sport Event. In the case of a Multiple Entry Contest, a Participant may enter more than one Team in a single Multiple Entry Contest, however on submitting more than one Team for participation in a single Multiple Entry Contest, the Participant will not be permitted to edit or revise the Teams so submitted for participation in such Multiple Entry Contest. In addition, it is expressly clarified that Gullypro may, from time to time, restrict the maximum number of Teams that may be created by a single User account (for each format on the Gullypro Site) or which a single User account may enter in a particular Multiple Entry Contest, in each case to such number as determined by Gullypro in its sole discretion.</span></p>
                    <p><span style={{fontWeight: 400}}>Gullypro shall collect a pre-designated fee for access to the amusement facilities from each Participant in relation to the Contest(s). In the event a Participant indicates, while entering an address, that he/she is a resident of either one of the Excluded States. Such User/Participant will not be permitted to proceed to sign up for the round or league and may not participate in any paid version of the Contest(s)</span></p>
                    <p><span style={{fontWeight: 400}}>FANTASY FORMATS</span></p>
                    <p><span style={{fontWeight: 400}}>Gullypro provides game/tournament/Contest(s) in two separate formats on the Gullypro Site, (1) as a public league where Users can participate in a game/tournament/Contest with other Users without any restriction on participation and (2) private leagues, where Users can invite specific Users into a game/tournament/Contest and restrict participation to such invited Users. All rules applicable to game/tournament/Contest(s) as set out herein shall be applicable to both formats of the game/tournament/Contest(s).</span></p>
                    <ol>
                    <li><span style={{fontWeight: 400}}> Public League</span></li>
                    </ol>
                    <p><span style={{fontWeight: 400}}>(i). In the Public League format of the game/tournament/Contest(s), Gullypro may offer the game/tournament/Contest(s) in leagues comprising of 2 Participants, 3 Participants, 5 Participants, 10 Participants, 100 Participants or any other pre-designated number of Participants. Gullypro may offer this format of the game/tournament/Contest(s) as a paid format and the Winner will be determinable at the end of the round.</span></p>
                    <p><span style={{fontWeight: 400}}>(ii). In certain game/tournament/Contests across the Gullypro Site, designated as "Confirmed Leagues", the game/tournament/Contest(s) shall become operational once the number of Participants in such game/tournament/Contest (s) equals the pre-specified number of winners to be declared in such game/tournament/Contest(s), even if all available Participant slots (as pre-specified in relation to the game/tournament/Contest(s)) remain unfilled. It is clarified that notwithstanding the activation of such game/tournament/Contest(s), Participants can continue to join such game/tournament/Contest(s) till either (i) all available Participant slots of such game/tournament/Contest(s) are filled; or (ii) the round to which the game/tournament/Contest (s) relates commences; whichever is earlier. In case such game/tournament/Contest(s) is not operational by the time of the commencement of the round, the participation fee paid by each Participant shall be returned to the account of such User without any charge or deduction.</span></p>
                    <ol>
                    <li><span style={{fontWeight: 400}}> Private League</span></li>
                    </ol>
                    <p><span style={{fontWeight: 400}}>(i). In the Private League format of the game/tournament/Contest(s), Gullypro enables Users to create a league ("Private League") and invite other users, whether existing Users or otherwise, ("Invited User") to create Teams and participate in the game/tournament/Contest(s). Users may create a Private League to consist of a pre-specified number of Participants, that is, consisting of either 2 Participants, 3 Participants, 5 Participants or 10 Participants. The User creating the Private League shall submit the participation fee for such Private League and thereby join that Private League, shall supply a name for the Private League and be provided with a unique identification code ("League Code") (which will be issued to the account of such User). The User agrees and understands that once the Private League is created no change shall be permitted in the terms or constitution of the Private League, except for a change in the name of the League.</span></p>
                    <p><span style={{fontWeight: 400}}>(ii). In order to participate in the Private League, an Invited User shall input the League Code associated with the Private League and submit the participation fee for the Private League. Once the number of Participants in a Private League equals the number of pre-specified Participants for that Private League, the Private League shall be rendered operative and no other Invited Users or Users shall be permitted to participate in the Private League. In the event that any Private League does not contain the pre-specified number of Participants for that Private League within one (1) hour prior to the commencement of the round/Contest, the league will get cancelled and the amount will get deposited in the Gullypro account.</span></p>
                    <p><span style={{fontWeight: 400}}>(iii). It is clarified that the participation of Invited Users in any Private League is subject to the pre-specified number of Users/Participants for that Private League, and Gullypro shall not be liable to any person for the inability of any Invited User to participate in any Private League due to any cause whatsoever, including without limitation due to a hardware or technical malfunction or lack of eligibility of such Invited User to participate in the game/tournament/Contest(s).</span></p>
                    <p><span style={{fontWeight: 400}}>Specific Terms for fantasy formats or alternative tournaments that are specially curated will be affixed as Schedules to the Terms &amp; Conditions, from time to time, as necessary and applicable by Gullypro.</span></p>
                    <p><span style={{fontWeight: 400}}>TABULATION OF FANTASY POINTS</span></p>
                    <p><span style={{fontWeight: 400}}>Gullypro may obtain the score feed and other information required for the computation and tabulation of fantasy points from third party service provider(s) with appropriate licenses. In the rare event that any error in the computation or tabulation of fantasy points, selection of winners, etc. as a result of inaccuracy in or incompleteness of the feed provided by the third-party service provider comes to its attention, Gullypro shall use best efforts to rectify such error prior to the distribution of prizes. However, Gullypro hereby clarifies that it relies on the accuracy and completeness of such third party score/statistic feeds and does not itself warrant or make any representations concerning the accuracy thereof and, in any event, shall take no responsibility for inaccuracies in computation and tabulation of fantasy points or the selection of winners as a result of any inaccurate or incomplete scores/statistics received from such third- party service provider. Users/Participants agree not to make any claim or raise any complaint against Gullypro in this respect.</span></p>
                    <p><span style={{fontWeight: 400}}>PAYMENT TERMS</span></p>
                    <p><span style={{fontWeight: 400}}>In respect of any transactions entered into on the Gullypro Site, including making a payment to participate in the paid versions of game/tournament/Contest(s), Users agree to be bound by the following payment terms.</span></p>
                    <p><span style={{fontWeight: 400}}>The payment Users make to participate in the game/tournament/Contest(s) is inclusive of the nominated fee for access to the games/contests/tournaments on the Gullypro Site charged by Gullypro. Subject to these Terms and Conditions, all other amounts collected from the User are held in escrow until determination of the Winners and distribution of prizes.</span></p>
                    <p><span style={{fontWeight: 400}}>Gullypro provides users with three categories of accounts for the processing and reconciliation of payments in relation to the Gullypro Site: (i) 'Deposit' Account, (ii) Winnings Account, and (iii) Cash Bonus Account.</span></p>
                    <p><span style={{fontWeight: 400}}>The User's winnings in any game/tournament/Contest will reflect as credits to the User's Winnings Account. It is clarified that in no instance will Gullypro permit the transfer of any amounts in the User's accounts to any other category of account held by the user with Gullypro or any third-party account, including a bank account held by a third party.</span></p>
                    <p><span style={{fontWeight: 400}}>Users shall be required to remit the required amount to Gullypro through the designated payment gateway. The payment made shall be credited to the User's accounts and each time a User enters a round, the applicable amount towards participation in the round shall be debited from the User's account. In debiting amounts from the User's accounts towards the participation fee of such user in any round or game/tournament/Contest(s), Gullypro shall first debit the User's 'Deposit' Account, thereafter, any remaining amount of participation fee shall be debited from the User's Cash Bonus Account and thereafter, any remaining amount of participation fee shall be debited from the User's Winning Account. In case there is any amount remaining to be paid by the User in relation to such User's participation in any round(s) or game/tournament/Contest(s), the User will be taken to the designated payment gateway to give effect to such payment. In case any amount added by the User through such payment gateway exceeds the remaining amount of participation fee, the amount in excess shall be transferred to the User's 'Deposit' Account and will be available for use in participation in any round(s) or Contest(s) or for withdrawal in accordance with these Terms and Conditions. Debits from the 'Deposit' Account for the purpose of enabling a user's participation in a Contest shall be made in order of the date of credit of amounts in the 'Deposit' Account, and accordingly amounts credited into 'Deposit' Account earlier in time shall be debited first.</span></p>
                    <p><span style={{fontWeight: 400}}>A User shall not be permitted to withdraw any amounts credited into such User's 'Deposit' Account for any reason whatsoever. All amounts credited into a User's 'Deposit' Account must be utilised within 335 days of credit. In case any Deposit amount lies in the 'Deposit' Account after the completion of 335 days from the date of credit of such amount, Gullypro reserves the right to forfeit such Deposit amount, without liability or obligation to pay any compensation to the User.</span></p>
                    <p><span style={{fontWeight: 400}}>Withdrawal of any amount standing to the User's credit in the Winnings Account may be made by way of a request to Gullypro at info@gullypro.com but shall occur automatically upon completion of the said 335 days from the date of credit of such amount in the User's Winnings Account. In either case, Gullypro shall effect an online transfer to the User's bank account on record with Gullypro within a commercially reasonable period of time. Such transfer will reflect as a debit to the User's Winnings Account. Gullypro shall not charge any processing fee for the online transfer of such amount from the Winnings Account to the User's bank account on record with Gullypro.</span></p>
                    <p><span style={{fontWeight: 400}}>Users are requested to note that they will be required to provide valid PAN CARD to allow Gullypro to process the withdrawal request. The name mentioned on the User's PAN CARD must correspond with the name provided by the User at the time of registration on www.gullypro.com, as well as the name and address existing in the records of the User's bank account as provided to www.gullypro.com. In the event that no bank account has been registered by the User against such User's account with www.gullypro.com, or the User has not verified his/her User account with www.gullypro.com, to Gullypro’s satisfaction and in accordance with these Terms and Conditions. Gullypro shall provide such User with a notification to the User's email address as on record with www.gullypro.com at least thirty (30) days prior to the Auto Transfer Date, and in case the User fails to register a bank account with his/her User Account and/or to verify his/her User Account by the Auto Transfer Date, Gullypro shall be entitled to forfeit any amounts subject to transfer on the Auto Transfer Date. Failure to provide Gullypro with a valid bank account and/or valid identification documents (to Gullypro’s satisfaction) may result in forfeiture of any amounts subject to transfer in accordance with this clause.</span></p>
                    <p><span style={{fontWeight: 400}}>The Cash Bonus Account shall contain amounts gratuitously issued by Gullypro to the User for use in participation in any game/tournament/Contest(s) and no User shall be permitted to transfer or request the transfer of any amount in to the Cash Bonus Account. The usage of any amounts issued and present in the Cash Bonus Account shall be subject to the limitations and restrictions, including without limitation, restrictions as to time within which such amount must be used, as applied by Gullypro and notified to the User at the time of issue of such amount. The issue of any amount to the Cash Bonus Account is subject to the sole discretion of Gullypro and cannot be demanded by any User as a matter of right. Users agree that once they confirm a transaction on www.gullypro.com, they shall be bound by and make payment for that transaction.</span></p>
                    <p><span style={{fontWeight: 400}}>A transaction, once confirmed, is final and no cancellation is permissible. However, www.gullypro.com may, at its sole and absolute discretion, permit a User to cancel a transaction and refund the amount paid.</span></p>
                    <p><span style={{fontWeight: 400}}>TAXES PAYABLE</span></p>
                    <p><span style={{fontWeight: 400}}>All prizes shall be subject to deduction of tax ("TDS") as per the Income Tax Act 1961. The TDS rate prescribed by the Government of India with respect to any prize money amount that is more than INR 10,000/- (Indian Rupees Ten Thousand Only) is 30% of the total prize money amount.</span></p>
                    <p><span style={{fontWeight: 400}}>In case of any revisions by the Government of India to the aforementioned rate in the future, TDS will be deducted by Gullypro in accordance with the then current prescribed TDS rate. Winners will be provided TDS certificates in respect of such tax deductions.</span></p>
                    <p><span style={{fontWeight: 400}}>The Winners shall be responsible for payment of any other applicable tax, including but not limited to, income tax, gift tax, etc. in respect of the prize money.</span></p>
                    <p><span style={{fontWeight: 400}}>SELECTION AND VERIFICATION OF WINNERS AND CONDITIONS FOR PRIZES</span></p>
                    <p><span style={{fontWeight: 400}}>SELECTION OF WINNERS</span></p>
                    <p><span style={{fontWeight: 400}}>(i). Winners shall be decided by the scores of the Teams in a designated match of the game/tournament/Contest(s). The User(s)/Participant(s) owning the Team(s) with the highest aggregate score in a match shall be declared the Winner(s). In certain pre-specified game/tournament/Contests, Gullypro may declare more than one Winner and distribute prizes to such Winners in increasing order of their Team's aggregate score at the end of the designated match of the game/tournament/Contest. The contemplated number of Winners and the prize due to each Winner in such game/tournament/Contest shall be as specified on the game/tournament/Contest page prior to the commencement of the game/tournament/Contest.</span></p>
                    <p><span style={{fontWeight: 400}}>(ii). Users/Participants creating Teams on behalf of any other User/Participant or person shall be disqualified.</span></p>
                    <p><span style={{fontWeight: 400}}>(iii). In the event of a tie, the winning Users/Participants shall be declared Winners and the prize shall be equally divided among such Users/Participants.</span></p>
                    <p><span style={{fontWeight: 400}}>(iv). Gullypro shall not be liable to pay any prize if it is discovered that the Winner(s) have not abided by these Terms and Conditions, and other rules and regulations in relation to the use of the Gullypro, game/tournament/Contest, "Fantasy Rules", etc.</span></p>
                    <p><span style={{fontWeight: 400}}>CONTACTING WINNERS</span></p>
                    <p><span style={{fontWeight: 400}}>(i). Winners shall be contacted by Gullypro or the third party conducting the game/tournament/Contest on the email address provided at the time of registration. The verification process and Mandatory Information Documents (MIDs) shall be required for the collection of prize(s).</span></p>
                    <p><span style={{fontWeight: 400}}>"Mandatory Information Documents (MIDs)"&nbsp;shall include the following documents:</span></p>
                    <p><span style={{fontWeight: 400}}>(a). PAN Card;</span></p>
                    <p><span style={{fontWeight: 400}}>(b). Government-issued residence proof; and</span></p>
                    <p><span style={{fontWeight: 400}}>(c). Details of the payment settlement system used by the User.</span></p>
                    <p><span style={{fontWeight: 400}}>(ii). Gullypro shall not permit a Winner to withdraw his/her prize(s)/accumulated winnings unless the above-mentioned documents have been received and verified within the time-period stipulated by Gullypro. The User represents and warrants that the documents provided in the course of the verification process are true copies of the original documents to which they relate.</span></p>
                    <p><span style={{fontWeight: 400}}>(iii). Users/Participants are required to provide proper and complete details at the time of registration. Gullypro shall not be responsible for communications errors, commissions or omissions including those of the Users/Participants due to which the results may not be communicated to the Winner.</span></p>
                    <p><span style={{fontWeight: 400}}>(iv). The list of Winners for each game/tournament/Contest(s) shall be posted on the platform. The winners will also be intimated by e-mail.</span></p>
                    <p><span style={{fontWeight: 400}}>(v). If a User/Participant has been declared a Winner on the platform but has not received any communication from Gullypro, such User/Participant may contact Gullypro within twenty-four (24) hours of such User/Participant being declared the Winner.</span></p>
                    <p><span style={{fontWeight: 400}}>VERIFICATION PROCESS</span></p>
                    <p><span style={{fontWeight: 400}}>(i). Only those Winners who successfully complete the verification process and provide the required documents within the time limit specified by Gullypro shall be permitted to withdraw/receive their accumulated winnings (or any part thereof). Gullypro shall not entertain any claims or requests for extension of time for submission of documents.</span></p>
                    <p><span style={{fontWeight: 400}}>(ii). Gullypro shall scrutinise all documents submitted and may, at its sole and absolute discretion, disqualify any Winner from withdrawing his accumulated winnings (or any part thereof) on the following:</span></p>
                    <p><span style={{fontWeight: 400}}>(a). Determination by Gullypro that any document or information submitted by the User/Participant is incorrect, misleading, false, fabricated, incomplete or illegible;</span></p>
                    <p><span style={{fontWeight: 400}}>(b). User/Participant does not fulfill the participation criteria as specified under these Terms and Conditions;</span></p>
                    <p><span style={{fontWeight: 400}}>(c). Any other thing.</span></p>
                    <p><span style={{fontWeight: 400}}>STANDARD TERMS &amp; CONDITIONS FOR PROMOTIONS</span></p>
                    <p><span style={{fontWeight: 400}}>These standard terms and conditions of promotions (“Standard Terms”) supplement the terms of promotions undertaken on the Gullypro Site and which reference these Standard Terms (each a “Promotion”):</span></p>
                    <p><span style={{fontWeight: 400}}>Participation in any Promotion will be subject to a user complying with the Promotion Terms implemented by Gullypro in respect of such Promotion (“Promotion Terms”) and these Standard Terms. By participating in any Promotion, the participant further consents to and agrees to adhere with the terms and conditions of the Gullypro Site and Gullypro’s Privacy Policy.</span></p>
                    <p><span style={{fontWeight: 400}}>The Promotions are only open to users in India (except the residents of the Excluded States). Participation in the Promotions by proxy is not permitted. Participation in the Promotions is voluntary. Participation in one Promotion does not guarantee that such user will be eligible to participate in another Promotion. A user may participate in a Promotion and avail of each Promotion only through one account. An existing user of Gullypro shall not register a new account or operate more than one user account with gullypro or participate in a Promotion by registering a new account. Users intending to participate in a Promotion may be required to verify their mobile number and other account details in accordance with the Promotion Terms for such Promotion.</span></p>
                    <p><span style={{fontWeight: 400}}>Persons intending to participate in a Promotion, who have listed their phone numbers on the National Do Not Call Registry (“NDNC Registry”), shall de-register themselves from the NDNC Registry till the completion of such Promotion (including the delivery of Bonus Amount (if any) or the free-entry (if any) under such Promotion). Such persons agree not to make any claim or raise any complaint whatsoever against Gullypro in this respect. Please note that persons intending to participate in a Promotion who have not de-registered themselves from the NDNC Registry shall also have no right to make any claim or raise any complaints against Gullypro if they do or do not receive any call or SMS with respect to their participation and all other matters pertaining to a Promotion.</span></p>
                    <p><span style={{fontWeight: 400}}>The verification process may require you to submit personal information about yourself. You agree to receive communication from Gullypro. Any information collected in respect of your identity and contact details as part of a Promotion or otherwise in the course of your use of the Gullypro Site shall be subject to Gullypro’s Privacy Policy.</span></p>
                    <p><span style={{fontWeight: 400}}>Gullypro may, at its sole and absolute discretion, disqualify any user from a Promotion if such user engages in or it is found that such user has engaged in any illegal, unlawful or improper conduct (with regard to any of the Promotions or otherwise).</span></p>
                    <p><span style={{fontWeight: 400}}>The Bonus Amount (if any) deposited into the user’s account can be used to join paid leagues and contests on the Gullypro Site. However, the Bonus Amount (if any) cannot be: (i) used to join 2-member leagues; or (ii) withdrawn or transferred to any other cash balance account held by you with Gullypro or to any third-party account or to any bank/payment instrument account.</span></p>
                    <p><span style={{fontWeight: 400}}>STANDARD TERMS &amp; CONDITIONS FOR PROMOTIONS</span></p>
                    <p><span style={{fontWeight: 400}}>This “Cashback Promotion” (“Promotion"), is open for participation to existing users of Gullypro who have not previously participated in a pay-to-play league on Gullypro. Users are required to make a deposit and participate on Gullypro platform fantasy cricket game through either (i) the Gullypro website or (ii) the ‘Pro’ version of www.gullypro.com’s mobile application for iOS and/or Android mobile devices, (collectively, the “Designated Platforms”), to be eligible to receive a Bonus Amount credited into their Cash Bonus Account, subject to these Terms.</span></p>
                    <p><span style={{fontWeight: 400}}>This “Cashback Promotion” (“Promotion"), is open for participation to existing users of Gullypro who have not previously participated in a pay-to-play league on Gullypro. Users are required to make a deposit and participate on Gullypro platform fantasy cricket game through either (i) the Gullypro website or (ii) the ‘Pro’ version of www.gullypro.com’s mobile application for iOS and/or Android mobile devices, (collectively, the “Designated Platforms”), to be eligible to receive a Bonus Amount credited into their Cash Bonus Account, subject to these Terms.</span></p>
                    <p><span style={{fontWeight: 400}}>Please note our terms and conditions (“Terms”) in this respect, as they govern your participation in the Promotion:</span></p>
                    <p><span style={{fontWeight: 400}}>(a).&nbsp;Eligibility&nbsp;– Participation in the Promotion is only available to users who are not existing users of Gullypro, and who are eligible to participate in the pay-to play Gullypro fantasy games (as per Gullypro’s Terms &amp; Condition (accessible at https://www.gullypro.com/terms.html ). Participation in the promotion is only open to a user who has received a banner concerning the Promotion from Gullypro (“Promotion Banner”) while visiting the Gullypro Site.</span></p>
                    <p><span style={{fontWeight: 400}}>An ‘existing user of Gullypro’ shall mean a user who presently operates an account with the Gullypro Site or has operated an account with Gullypro at any point of time.</span></p>
                    <p><span style={{fontWeight: 400}}>(b). By participating in the Promotion, you agree to comply with these Terms, the Standard Terms and Conditions for Promotions and the Terms &amp; Conditions of the Gullypro Site (accessible at https://www.gullypro.com/terms.html ).</span></p>
                    <p><span style={{fontWeight: 400}}>(c). The Promotion will be open for participation for such time periods as may be published from time to time on the Gullypro Site (each a “Promotion Period”).</span></p>
                    <p><span style={{fontWeight: 400}}>(d). To participate in the Promotion, you shall, during the Promotion Period and before the expiry of the Promotion Period register and create an account with Gullypro through the Gullypro Site and participate in the First Game (defined below) before the expiry of the applicable Promotion Period. The Promotion is available only in respect of the Gullypro fantasy cricket league that the participating user, who is not an existing user of Gullypro, participates in through the Gullypro Site after the registration of such user’s account with Gullypro (“First Game”). Upon joining the First Game, you will receive an email on your email address as registered with your Gullypro account, which email will summarize the terms and mechanics of the Promotion.</span></p>
                    <p><span style={{fontWeight: 400}}>(e). After the completion of your participation in the First Game and in the event that your winnings (if any) from the First Game are less than the entry fees paid by you to enter the First Game, you shall be eligible to receive a cash bonus equal to the entry fee paid by you for participation in the First Game after deduction of any winnings received by you pursuant to your participation in the First Game (“Bonus Amount”). The maximum Bonus Amount creditable under this Promotion shall be an amount of INR. 50. A user shall be eligible to receive the Bonus Amount only in case the difference between the entry fees paid by the user for such user’s participation in the First Game and the winnings (if any) received by the user from such First Game is a positive figure.</span></p>
                    <p><span style={{fontWeight: 400}}>(f). A participating user is required to pay the entire entry fee for the First Game from such user’s “Deposit” account to be eligible to receive the Bonus Amount. In the event that a user pays the entry fee for the First Game, either in whole or in part, by using any amounts deposited in such user’s Cash Bonus Account, such user will not be eligible to receive the Bonus Amount.</span></p>
                    <p><span style={{fontWeight: 400}}>(g). It is clarified that a participating user shall not be eligible to receive any Bonus Amount for: (i) any non-cricket pay-to-play Gullypro league in which such user participates; or (ii) any pay-to-play Gullypro league in which such user participates through platforms other than the Gullypro Site; or (iii) any pay-to-play Gullypro league in which such user participates after the First Game or after the applicable Promotion Period; or (iv) any private pay-to-play Gullypro league in which such user participates; or (v) any pay-to-play Gullypro league in which such user participates and which remains unfilled prior to the commencement of the match to which it relates; or (vi) any pay-to-play Gullypro league in which such user participates and which is cancelled by Gullypro due to the match to which it relates being abandoned.</span></p>
                    <p><span style={{fontWeight: 400}}>(h). The selection of recipients of the Promotion Banner shall be as per Gullypro’s discretion and determination, and no person shall claim or demand a Promotion Banner or seek participation in the Promotion as a matter of right.</span></p>
                    <p><span style={{fontWeight: 400}}>STANDARD TERMS AND CONDITIONS OF "INVITE A FRIEND" PROGRAM</span></p>
                    <p><span style={{fontWeight: 400}}>The Gullypro Get a Friend Program lets you invite friends to join Gullypro (“Program”). In the event that you and your referred friend meet the criteria and complete all the steps specified in these terms, you and your friend can earn a Cash Bonus from Gullypro of upto RsINR. 100/- (“Bonus Amount”), which Bonus Amount will be redeemable to join paid leagues and contests through the ‘Pro’ version of Gullypro’s Site for the iOS and/or Android mobile devices (“Pro Application”). To participate in the Program, please note our terms and conditions (“Terms”) in this respect, as they govern your participation in the Program:</span></p>
                    <p><span style={{fontWeight: 400}}>(a).&nbsp;Eligibility&nbsp;– All users who: (i) have an account registered with Gullypro’s Site which account has been verified by Gullypro; and (ii) are eligible to participate in the pay-to play Gullypro fantasy cricket (as per the Gullypro Terms &amp; Conditions) and (iii) have downloaded and installed the Pro Application on their respective mobile devices, will be eligible to participate in the Program. Participation in the Program by proxy is not permitted.</span></p>
                    <p><span style={{fontWeight: 400}}>(b). The Inviter and the Invitee will be eligible to earn the Bonus Amount subject to (amongst other terms specified in these Terms): (i) the Invitee not being an existing user of Gullypro; and (ii) the Inviter and Invitee being eligible to participate in the pay-to play Gullypro contests and/or tournaments; and (iii) the Invitee successfully registering for an account with Gullypro through the unique link or by using the unique code shared by the Inviter; and (iv) the Inviter and Invitee agreeing to the license agreement for the Pro Application and downloading and installing the Pro Application as available for the Inviter’s and Invitee’s respective mobile devices.</span></p>
                    <p><span style={{fontWeight: 400}}>PRIVACY POLICY</span></p>
                    <p><span style={{fontWeight: 400}}>The User hereby consents and agrees that she/he has read and fully understood the contents and terms of the Privacy Policy of Gullypro and by using the Gullypro Site, the User has consented to such content and terms of the Privacy Policy of Gullypro. Our Privacy Policy (which shall be available at https://www.gullypro.com/privacy.html ) shall apply to all the entries to the Games/tournaments/contests and the Services on the Website.</span></p>
                    <p><span style={{fontWeight: 400}}>INTELLECTUAL PROPERTY RIGHTS</span></p>
                    <p><span style={{fontWeight: 400}}>Unless otherwise stated, copyright and/or all intellectual property rights in all Materials on the Gullypro site (including but not limited to text, audio, video or graphical images, or technology, the look and feel of the Gullypro site), trademarks and logos appearing on the Gullypro site are the properties of Gullypro and are owned &amp; controlled by us and/or by other parties that have licensed their material to us. You shall not copy, reproduce, republish, upload, post, transmit or distribute the Gullypro site Material in any way, including by e-mail and/or other electronic means and whether directly or indirectly and/or assist any other person to do the same. Without the prior written consent of the owner of the Materials, modification, use of the Materials on any other web site and/or networked computer environment and/or use of the Materials for any purpose other than personal, non-commercial use shall be considered a violation of the copyrights, trademarks and other proprietary rights of Gullypro and shall be prohibited.</span></p>
                    <p><span style={{fontWeight: 400}}>Any use of the Material other than for personal and non-commercial purposes shall be considered as commercial use for the purposes of this clause. You agree not to use any framing techniques to enclose any trademark or logo or other proprietary information of Gullypro or remove, conceal or obliterate any copyright or other proprietary notice or any credit-line or date-line on other mark or source identifier included on the Gullypro site, including without limitation, the size, colour, location or style of all proprietary marks. Any infringement shall be vigorously defended and pursued to the extent permitted by law.</span></p>
                    <p><span style={{fontWeight: 400}}>We, at Gullypro, respect other people's intellectual property rights and if you believe that any content or material on the Gullypro site infringes on your intellectual property rights, you can write and inform us about the same at info@gullypro.com.</span></p>
                    <p><span style={{fontWeight: 400}}>ADVERTISING MATERIAL</span></p>
                    <p><span style={{fontWeight: 400}}>Some part of the Gullypro site, may contain advertising information, surveys, promotional material or other material submitted to Gullypro by third parties. Responsibility for ensuring that the material submitted for inclusion on the Gullypro site complies with the applicable law is exclusively on the party providing the information/material. Your correspondence or business dealings with, or participation in the promotions of advertisers or including the payment and delivery of related goods or services, and/or any other terms, conditions, warranties or representations associated with such dealings, are solely between You and such advertisers. Gullypro shall not be responsible and/or liable for any claim, error, omission, inaccuracy in advertising material and/or any loss or damage of any sort incurred as a result of any such dealings or as a result of the presence of such advertisers on the Gullypro site. Gullypro reserves the right to omit, suspend or change the position of any advertising material submitted for insertion.</span></p>
                    <p><span style={{fontWeight: 400}}>LIMITATION OF LIABILITY</span></p>
                    <p><span style={{fontWeight: 400}}>In no event shall Gullypro, its officers, directors, employees, or agents, be liable to you for any direct, indirect, incidental, special, punitive, or consequential damages whatsoever resulting from any:</span></p>
                    <p><span style={{fontWeight: 400}}>(i). errors, mistakes, or inaccuracies of content;</span></p>
                    <p><span style={{fontWeight: 400}}>(ii). personal injury or property damage, of any nature whatsoever, resulting from your access to and use of our service;</span></p>
                    <p><span style={{fontWeight: 400}}>(iii). any unauthorized access to or use of our secure servers and/or any and all personal information and/or financial information stored therein;</span></p>
                    <p><span style={{fontWeight: 400}}>(iv). any interruption and/or cessation of transmission to or from our servers;</span></p>
                    <p><span style={{fontWeight: 400}}>(v). any bugs, viruses, trojan horses, or the like, which may be transmitted to or through our service by any third party;</span></p>
                    <p><span style={{fontWeight: 400}}>(vi). any errors or omissions in any content or for any loss or damage of any kind incurred as a result of your use of any content posted, emailed, transmitted, or otherwise made available via the Gullypro client, whether based on warranty, contract, tort, or any other legal theory, and whether or not Gullypro is advised of the possibility of such damages; and/or</span></p>
                    <p><span style={{fontWeight: 400}}>(vii).the disclosure of information pursuant to these Terms and Conditions or privacy policy of Gullypro. The foregoing limitation of liability shall apply to the extent permitted by law in the applicable jurisdiction.</span></p>
                    <p><span style={{fontWeight: 400}}>You specifically acknowledge that Gullypro shall not be liable for any defamatory, offensive, or illegal conduct of any third party and that the risk of any harm or damage from the foregoing shall rest entirely with you.</span></p>
                    <p><span style={{fontWeight: 400}}>TECHNICAL FAILURES AND DISCONNECTION POLICY</span></p>
                    <p><span style={{fontWeight: 400}}>It is possible that you may face disruptions, including, but not limited to errors, disconnection or inferences in communication in the Internet services, software or hardware that you have used to avail our services.</span></p>
                    <p><span style={{fontWeight: 400}}>Gullypro shall not be liable for any network outages or any problems/interruptions with network connectivity including network, Internet services, computer hardware or software failures of any kind in the disruption in the services as the same is beyond Gullypro’s control. You take full responsibility with complete knowledge for any risk of loss or damages caused due to interruption of services for any such reasons.</span></p>
                    <p><span style={{fontWeight: 400}}>You agree that Gullypro shall not be held responsible and/or liable for any interruption in an Gullypro game and/or tournament and/or contest caused at the User’s end due to an incoming call, message, chat, video call or any other interruption on the mobile phone device/tablet device. In case of any interruption specified above in an Gullypro game and/or tournament and/or Contest on the User’s mobile phone device/tablet device, the game and/or tournament and/or contest shall still continue, and the User shall assume complete responsibility for such interruptions in between the games and/or tournaments and/or contests.</span></p>
                    <p><span style={{fontWeight: 400}}>INDEMNITY</span></p>
                    <p><span style={{fontWeight: 400}}>You agree to defend, indemnify and hold harmless Gullypro, its officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from: (i) your use of and access to the Gullypro site; (ii) your violation of any term of these Terms and Conditions; (iii) your violation of any third party rights, including without limitation any trademark, copyright, property, or any other privacy rights; (iv) any violation of applicable law, rules, regulations, orders and ordinances. This defence and indemnification obligation shall survive these Terms and Conditions.</span></p>
                    <p><span style={{fontWeight: 400}}>CHARGEBACK POLICY</span></p>
                    <p><span style={{fontWeight: 400}}>“Chargeback”&nbsp;is a credit card charge that has been disputed or claimed as fraud with a credit card company and/or the User’s bank. A credit card chargeback occurs after a cardholder/User(s) initiates a merchant dispute with their issuing bank and the issuing bank will then charge back the transaction being disputed from Gullypro and the cardholder's account is credited.</span></p>
                    <p><span style={{fontWeight: 400}}>Chargeback, as defined above, may occur for one of the following reasons:</span></p>
                    <ol>
                    <li><span style={{fontWeight: 400}}> Mistakenly filed by the cardholder/User as he/she did not recognize the charge;</span></li>
                    <li><span style={{fontWeight: 400}}> Many User(s) request friends, parents or other relatives to pay for the game, and they may misunderstand the billing policy and/or do not recognize the charges. They may then file a dispute for the fees;</span></li>
                    <li><span style={{fontWeight: 400}}> After a credit card is lost or stolen, the User or bank disputes the charges in error;</span></li>
                    <li><span style={{fontWeight: 400}}> An account is sold, shared, transferred or traded and the previous owner disputes previous billing fees. These types of accounts can and will not be released;</span></li>
                    <li><span style={{fontWeight: 400}}> Technical problems during the payment processes; and</span></li>
                    <li><span style={{fontWeight: 400}}> Fraudulent use of a credit card.</span></li>
                    </ol>
                    <p><span style={{fontWeight: 400}}>Procedure for User(s) recovering his/her account following Chargeback</span></p>
                    <ol>
                    <li><span style={{fontWeight: 400}}> The User(s) needs to verify his/her ownership of the account in question for a chargeback. The User may need to create a new account to do so.</span></li>
                    <li><span style={{fontWeight: 400}}> The User then needs to provide the following details:</span></li>
                    <li><span style={{fontWeight: 400}}> Name (as on the Government issued Identity Card):</span></li>
                    <li><span style={{fontWeight: 400}}> Username:</span></li>
                    <li><span style={{fontWeight: 400}}> Name on the Credit Card:</span></li>
                    <li><span style={{fontWeight: 400}}> The last 4 digits of the Credit Card used on the account:</span></li>
                    <li><span style={{fontWeight: 400}}> Current answer to security question:</span></li>
                    <li><span style={{fontWeight: 400}}> Email Address:</span></li>
                    <li><span style={{fontWeight: 400}}> In order to uphold the Gullypro privacy and security policies, representatives will ask you to verify information on an account. Payments shall not be accepted if the contact is not able to prove his/her ownership of the account. Missing information can cause delays and halt the recovery process. If the User requires additional time to gather the requested information, he/she should contact Gullypro at info@gullypro.com.</span></li>
                    <li><span style={{fontWeight: 400}}> If the User(s) does not remember the exact credit card number, he/she should check with the bank from whom the credit card was issued to the User. When an account is terminated and/or banned, the same shall not be renewed automatically on the Gullypro platform. All billing related to that User account shall be stopped.</span></li>
                    </ol>
                    <p><span style={{fontWeight: 400}}>Dispute of Charge by the User(s) with his/her bank:</span></p>
                    <p><span style={{fontWeight: 400}}>If the User has disputed a charge with his/her bank, Gullypro shall terminate and/or close the User’s account and place it under suspension until the payment is returned to Gullypro.</span></p>
                    <p><span style={{fontWeight: 400}}>User’s card charged without permission:</span></p>
                    <p><span style={{fontWeight: 400}}>Gullypro has no way of knowing who is charging the User’s credit card at the time of purchase. However, there are certain factors which shall establish whether or not the charge is from a legitimate source or is fraudulent in nature. In most cases Gullypro shall actively ban and refund charges to credit cards that Gullypro has determined to be fraudulent in nature. However, most of the chargeback claims are not legitimate and require remittance before the account can be used again.</span></p>
                    <p><span style={{fontWeight: 400}}>Friendly Fraud:</span></p>
                    <p><span style={{fontWeight: 400}}>Friendly Fraud occurs when a charge is placed by a member of a household with access to a credit card (or who has memorized the security information on a card) and placed charges which may not be known to the primary card holder. The charges shall still be counted as legitimate whether or not the primary card holder was aware of the charges.</span></p>
                    <p><span style={{fontWeight: 400}}>Process to be followed by Gullypro after verification of ownership</span></p>
                    <ol>
                    <li><span style={{fontWeight: 400}}> Once the User(s) has verified ownership, the Gullypro team in charge of the User(s) case shall give the User(s) instructions on how to proceed.</span></li>
                    <li><span style={{fontWeight: 400}}> The User(s) shall also remember that every case is different and that the Gullypro team will need to research exactly what happened to ensure that both the User(s) and Gullypro get the fairest result.</span></li>
                    </ol>
                    <p><span style={{fontWeight: 400}}>GOVERNING LAW AND JURISDICTION</span></p>
                    <p><span style={{fontWeight: 400}}>The Courts of competent jurisdiction at Delhi shall have exclusive jurisdiction to determine any and all disputes arising out of, or in connection with, the Gullypro services provided by Gullypro (including the game/tournament/Contest(s)), the construction, validity, interpretation and enforceability of these Terms and Conditions, or the rights and obligations of the User(s) (including Participants/Users) or Gullypro, as well as the exclusive jurisdiction to grant interim or preliminary relief in case of any dispute referred to arbitration as given below. All such issues and questions shall be governed and construed in accordance with the laws of the Republic of India.</span></p>
                    <p><span style={{fontWeight: 400}}>DISPUTE RESOLUTION</span></p>
                    <p><span style={{fontWeight: 400}}>If any question, issue, difference or dispute arises between the disputing parties as to the interpretation of these Terms and Conditions or as to the duties and/or liabilities of either Party to these Terms and Conditions hereunder or as to any matter and/or thing arising out of or under these Terms and Conditions, the party raising the dispute shall provide a written notification ("Notification") to the other party. On receipt of Notification, the parties shall first try to resolve the dispute through discussions.</span></p>
                    <p><span style={{fontWeight: 400}}>In the event that the parties are unable to resolve the dispute within fifteen (15) days of receipt of Notification, the dispute shall be settled by arbitration by a sole arbitrator to be appointed mutually by the disputing parties. The Arbitration proceedings shall be conducted at Delhi in accordance with the Indian Laws (both Substantive and Procedural) under the Arbitration and Conciliation Act, 1996 as amended and re-enacted from time to time and the Award so made shall be final and binding on all the parties. The language of arbitration proceedings shall be English.</span></p>
                    <p><span style={{fontWeight: 400}}>The arbitrator shall be entitled to pass interim orders and awards, including the orders for specific performance and such orders would be enforceable in competent courts. The arbitrator shall give a reasoned award.</span></p>
                    <p><span style={{fontWeight: 400}}>Nothing contained in these Terms and Conditions shall prevent Gullypro from seeking and obtaining interim or permanent equitable or injunctive relief, or any other relief available to safeguard Gullypro’s interest prior to, during or following the filing of arbitration proceedings or pending the execution of a decision or award in connection with any arbitration proceedings from any court having jurisdiction to grant the same. The pursuit of equitable or injunctive relief shall not constitute a waiver on the part of Gullypro to pursue any remedy for monetary damages through the arbitration described herein.</span></p>
                    <p><span style={{fontWeight: 400}}>REPRESENTATIONS AND WARRANTIES</span></p>
                    <p><span style={{fontWeight: 400}}>The User, not limiting his/her statutory rights, expressly acknowledges and agrees to the following:</span></p>
                    <p><span style={{fontWeight: 400}}>The User uses the Gullypro site at his or her own risk. Gullypro expressly disclaims all express or implied representations or warranties.</span></p>
                    <p><span style={{fontWeight: 400}}>Each User shall bear their own risk concerning all the gaming activities being undertaken by him/her through the Gullypro site.</span></p>
                    <p><span style={{fontWeight: 400}}>The User understands that certain delays can occur in Gullypro’s system/network and therefore he/she shall not hold Gullypro or any Gullypro provider, responsible for any system/network related problems.</span></p>
                    <p><span style={{fontWeight: 400}}>Gullypro does not guarantee, amongst other things that:</span></p>
                    <p><span style={{fontWeight: 400}}>the Game/Tournament/Contest and/or Gullypro Site will meet the user’s expectations;</span></p>
                    <p><span style={{fontWeight: 400}}>the Game/Tournament/Contest and/or Gullypro Site will be accessible without interruption or in a timely, reliable or fault-free manner;</span></p>
                    <p><span style={{fontWeight: 400}}>the results obtained through the use of the Game/Tournament/Contest and/or Gullypro Site will be correct and reliable;</span></p>
                    <p><span style={{fontWeight: 400}}>the quality of the products, services, information or other material purchased or obtained by the User through Game/Tournament/Contest and/or Gullypro Site will meet the User's expectations.</span></p>
                    <p><span style={{fontWeight: 400}}>The User shall be solely responsible for damages to his/her data system or for loss of data arising from downloads of content from the Game/Tournament/Contest and/or Gullypro Site.</span></p>
                    <p><span style={{fontWeight: 400}}>BREACH AND CONSEQUENCES</span></p>
                    <p><span style={{fontWeight: 400}}>If we have evidence of a breach of our Terms and Conditions through our investigations or reasonable belief that your continued access to our website/app (platform) is deleterious or detrimental to the interests of Gullypro and/or our Users or the general public, then we reserve the right in our sole discretion to take one or all of the actions as mentioned below:</span></p>
                    <p><span style={{fontWeight: 400}}>(a). Permanent suspension and/or termination of your User account on our platform;</span></p>
                    <p><span style={{fontWeight: 400}}>(b). Forfeit the balance amount left in your account;</span></p>
                    <p><span style={{fontWeight: 400}}>(c). Demand and order damages for breach of Gullypro Terms and Conditions and take required civil actions to recover damages;</span></p>
                    <p><span style={{fontWeight: 400}}>(d). Initiate steps of prosecution for damages and violation that is equivalent to offences in law;</span></p>
                    <p><span style={{fontWeight: 400}}>(e). Cause restriction to access our games/tournaments/contests to Users who are suspected in cases of cheating or colluding;</span></p>
                    <p><span style={{fontWeight: 400}}>(f). Bar you from playing or registering at Gullypro in the future, as we reserve full discretion to restrict you from playing our online fantasy games/tournaments/contests.</span></p>
                    <p><span style={{fontWeight: 400}}>The action taken by us will be solely due to your breach of our Terms and Conditions; the action shall be final and decisive that will be binding on you. Any action taken by us will be without prejudice to our other rights and remedies that are mentioned and available in law or equity.</span></p>
                    <p><span style={{fontWeight: 400}}>TERMINATION</span></p>
                    <p><span style={{fontWeight: 400}}>We reserve the right, at our discretion, to immediately, with or without notice, suspend or terminate your registration, the Terms and Conditions and/or your access to all or any portion of the Gullypro site and/or remove any registration information or User Content from the Gullypro site.</span></p>
                    <p><span style={{fontWeight: 400}}>Upon termination or expiration of the Terms and Conditions, your obligations and Gullypro’s rights and disclaimers survive, but your right to use the Gullypro site immediately ceases.</span></p>
                    <p><span style={{fontWeight: 400}}>DISCLAIMERS</span></p>
                    <p><span style={{fontWeight: 400}}>Gullypro shall make best endeavors to ensure that the site/platform (website/app) is error-free and secure. However, neither Gullypro nor any of its partners, licensors or associates make any warranty that:</span></p>
                    <p><span style={{fontWeight: 400}}>(a). The site/platform will meet Users’ requirements,</span></p>
                    <p><span style={{fontWeight: 400}}>(b). The site/platform will be uninterrupted, timely, secure, or error-free,</span></p>
                    <p><span style={{fontWeight: 400}}>(c). The results that may be obtained from the use of the site/platform will be accurate or reliable.</span></p>
                    <p><span style={{fontWeight: 400}}>Gullypro holds all the rights to rectify any errors identified in the determination of winners or in the transfer of amounts to a User's account, using various methods as it deems fit, including (but not limited to) through a set-off of the mistaken payment from amounts due to the User or deduction from the User's account of the amount of mistaken payment. In such events, Gullypro agrees to notify the User about the error and the rectification measures adopted to address the error.</span></p>
                    <p><span style={{fontWeight: 400}}>Complying to the legal bodies and authorities neither Gullypro nor its partners, licensors or associates disclaims any sort of responsibility for any direct, indirect, incidental, special, or consequential damages arising out of the use of or inability to use our sites, even if we have been advised of the possibility of such damages.</span></p>
                    <p><span style={{fontWeight: 400}}>Gullypro is authorized to cancel any events or contest(s) requiring specific permission or authority from any statutory authority or any State or the Central Government, or the board of directors or any events wherein such permission or authority is either not obtained or denied either before or after the organization of the relevant events or contest(s).</span></p>
                    <p><span style={{fontWeight: 400}}>By accepting these Terms and Conditions, the Users/Participants agree not to make any demands or claims in the event of suspension or closure of any services, events or game/tournament/contests organized/provided by Gullypro.</span></p>
                    <p><span style={{fontWeight: 400}}>FORCE MAJEURE</span></p>
                    <p><span style={{fontWeight: 400}}>Neither party to these Terms and Conditions shall be liable for any loss and/or any failure to perform any obligation under these Terms and Conditions due to causes beyond its reasonable anticipation or control including real or potential labour disputes, governmental actions, war or threat of war, sabotage, civil unrest, demonstrations, fire, storm, flooding, explosion, earthquake, provisions or limitations of materials or resources, inability to obtain the relevant authorization, accident and defect in electricity or telecommunication network, among other events.</span></p>
                    <p><span style={{fontWeight: 400}}>Force Majeure and/or another event beyond Gullypro’s control hindering, delaying or complicating the maintenance of the Gullypro Game/Tournament/Contest, shall entitle Gullypro to suspend or limit the Gullypro Game/Tournament/Contest until further notice.</span></p>
                    <p><span style={{fontWeight: 400}}>ENTIRE AGREEMENT</span></p>
                    <p><span style={{fontWeight: 400}}>The Terms and Conditions and Privacy Policy, as amended from time to time, constitute the entire agreement between you and Gullypro. If any provision of these Terms and Conditions is considered unlawful, void, or for any reason unenforceable by a court of competent jurisdiction, then that provision shall be deemed severable from these Terms and Conditions and shall not affect the validity and enforceability of any remaining provisions, which shall remain in full force and effect.</span></p>
                    <p><span style={{fontWeight: 400}}>ABILITY TO ACCEPT TERMS AND CONDITIONS</span></p>
                    <p><span style={{fontWeight: 400}}>You affirm that you are above eighteen (18) years of age and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms and Conditions, and to abide by and comply with these Terms and Conditions.</span></p>
                    <p><span style={{fontWeight: 400}}>Gullypro takes children's privacy seriously and always encourages parents and/or guardians to play an active role in their children’s online experience. Gullypro does not knowingly collect any personal information from children below the aforementioned age and if Gullypro learns that Gullypro has inadvertently gathered personal data from children under the aforementioned age, Gullypro shall take all reasonable measures to promptly delete such personal data from Gullypro’s records.</span></p>
                    <p><span style={{fontWeight: 400}}>You further represent and warrant that you are not located in any of the Excluded State in India where Gullypro is prohibited to be offered and/or accessed under the Indian laws.</span></p>
                    <p><span style={{fontWeight: 400}}>ASSIGNMENT</span></p>
                    <p><span style={{fontWeight: 400}}>These Terms and Conditions, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Gullypro without restriction.</span></p>
                    <p><span style={{fontWeight: 400}}>CHANGES TO TERMS AND CONDITIONS</span></p>
                    <p><span style={{fontWeight: 400}}>We reserve the right to modify these Terms and Conditions at any time. Any changes to the Terms and Conditions will be posted on the Gullypro site and it is your responsibility to review these Terms and Conditions for any changes. Your continued use of the Gullypro site following the posting of changes is your agreement to the changes/amendments and you shall be bound by the current and updated version of these Terms and Conditions.</span></p>
                    <p><span style={{fontWeight: 400}}>If any changes/amendments to these Terms and Conditions are unacceptable to you, you must discontinue the use of the services offered by Gullypro.</span></p>
                    <p><span style={{fontWeight: 400}}>We reserve the right to suspend or deny, in our sole discretion, your access to all or any portion of the Gullypro site, including for any violation of any provision of these Terms and Conditions. We also reserve the right to change the Gullypro site without notice to you, at any time.</span></p>
                    <p><span style={{fontWeight: 400}}>WAIVER</span></p>
                    <p><span style={{fontWeight: 400}}>No waiver of any term(s) of these Terms and Conditions shall be deemed a further or continuing waiver of such term or any other term and Gullypro’s failure to assert any right or provision under these Terms and Conditions shall not constitute a waiver of such right or provision.</span></p>
                    <p><span style={{fontWeight: 400}}>RELATIONSHIP</span></p>
                    <p><span style={{fontWeight: 400}}>None of the provisions of the Terms and Conditions shall be deemed to constitute a partnership or agency between you and Gullypro and you shall have no authority to bind Gullypro in any manner, whatsoever. If you are registering on the Gullypro site as a business entity, you represent that you have the authority to bind the entity to this Agreement.</span></p>
                    <p><br /><br /><br /></p>
            </div>
        </div>
        )
    }
}

export default termsandcondition
